import { z } from 'zod';
export declare const AuditActionSchema: z.ZodEnum<["CREATE", "READ", "UPDATE", "DELETE", "LOGIN", "LOGOUT", "APPROVE", "REJECT", "ASSIGN", "UNASSIGN", "EXPORT", "IMPORT", "UPLOAD", "DOWNLOAD", "SHARE", "ARCHIVE", "RESTORE", "OTHER"]>;
export type AuditAction = z.infer<typeof AuditActionSchema>;
export declare const AuditEntityTypeSchema: z.ZodEnum<["USER", "TEAM", "CASE", "PARTY", "HEARING", "ORDER", "TASK", "SUBTASK", "WORKLOG", "LEAVE_REQUEST", "DOCUMENT", "SYSTEM", "CONFIGURATION", "OTHER"]>;
export type AuditEntityType = z.infer<typeof AuditEntityTypeSchema>;
export declare const AuditSeveritySchema: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
export type AuditSeverity = z.infer<typeof AuditSeveritySchema>;
export declare const AuditLogSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodOptional<z.ZodString>;
    sessionId: z.ZodOptional<z.ZodString>;
    action: z.ZodEnum<["CREATE", "READ", "UPDATE", "DELETE", "LOGIN", "LOGOUT", "APPROVE", "REJECT", "ASSIGN", "UNASSIGN", "EXPORT", "IMPORT", "UPLOAD", "DOWNLOAD", "SHARE", "ARCHIVE", "RESTORE", "OTHER"]>;
    entityType: z.ZodEnum<["USER", "TEAM", "CASE", "PARTY", "HEARING", "ORDER", "TASK", "SUBTASK", "WORKLOG", "LEAVE_REQUEST", "DOCUMENT", "SYSTEM", "CONFIGURATION", "OTHER"]>;
    entityId: z.ZodOptional<z.ZodString>;
    entityName: z.ZodOptional<z.ZodString>;
    severity: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>>;
    description: z.ZodString;
    details: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    oldValues: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    newValues: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    ipAddress: z.ZodOptional<z.ZodString>;
    userAgent: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    resource: z.ZodOptional<z.ZodString>;
    method: z.ZodOptional<z.ZodEnum<["GET", "POST", "PUT", "PATCH", "DELETE"]>>;
    statusCode: z.ZodOptional<z.ZodNumber>;
    responseTime: z.ZodOptional<z.ZodNumber>;
    errorMessage: z.ZodOptional<z.ZodString>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isSensitive: z.ZodDefault<z.ZodBoolean>;
    retentionDate: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    description: string;
    tags: string[];
    action: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE";
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    isSensitive: boolean;
    userId?: string | undefined;
    location?: string | undefined;
    sessionId?: string | undefined;
    entityId?: string | undefined;
    entityName?: string | undefined;
    details?: Record<string, any> | undefined;
    oldValues?: Record<string, any> | undefined;
    newValues?: Record<string, any> | undefined;
    ipAddress?: string | undefined;
    userAgent?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
    responseTime?: number | undefined;
    errorMessage?: string | undefined;
    retentionDate?: Date | undefined;
}, {
    id: string;
    createdAt: Date;
    description: string;
    action: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE";
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    userId?: string | undefined;
    tags?: string[] | undefined;
    location?: string | undefined;
    sessionId?: string | undefined;
    entityId?: string | undefined;
    entityName?: string | undefined;
    severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
    details?: Record<string, any> | undefined;
    oldValues?: Record<string, any> | undefined;
    newValues?: Record<string, any> | undefined;
    ipAddress?: string | undefined;
    userAgent?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
    responseTime?: number | undefined;
    errorMessage?: string | undefined;
    isSensitive?: boolean | undefined;
    retentionDate?: Date | undefined;
}>;
export declare const CreateAuditLogSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    userId: z.ZodOptional<z.ZodString>;
    sessionId: z.ZodOptional<z.ZodString>;
    action: z.ZodEnum<["CREATE", "READ", "UPDATE", "DELETE", "LOGIN", "LOGOUT", "APPROVE", "REJECT", "ASSIGN", "UNASSIGN", "EXPORT", "IMPORT", "UPLOAD", "DOWNLOAD", "SHARE", "ARCHIVE", "RESTORE", "OTHER"]>;
    entityType: z.ZodEnum<["USER", "TEAM", "CASE", "PARTY", "HEARING", "ORDER", "TASK", "SUBTASK", "WORKLOG", "LEAVE_REQUEST", "DOCUMENT", "SYSTEM", "CONFIGURATION", "OTHER"]>;
    entityId: z.ZodOptional<z.ZodString>;
    entityName: z.ZodOptional<z.ZodString>;
    severity: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>>;
    description: z.ZodString;
    details: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    oldValues: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    newValues: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    ipAddress: z.ZodOptional<z.ZodString>;
    userAgent: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    resource: z.ZodOptional<z.ZodString>;
    method: z.ZodOptional<z.ZodEnum<["GET", "POST", "PUT", "PATCH", "DELETE"]>>;
    statusCode: z.ZodOptional<z.ZodNumber>;
    responseTime: z.ZodOptional<z.ZodNumber>;
    errorMessage: z.ZodOptional<z.ZodString>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isSensitive: z.ZodDefault<z.ZodBoolean>;
    retentionDate: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodDate;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    description: string;
    tags: string[];
    action: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE";
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    isSensitive: boolean;
    userId?: string | undefined;
    location?: string | undefined;
    sessionId?: string | undefined;
    entityId?: string | undefined;
    entityName?: string | undefined;
    details?: Record<string, any> | undefined;
    oldValues?: Record<string, any> | undefined;
    newValues?: Record<string, any> | undefined;
    ipAddress?: string | undefined;
    userAgent?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
    responseTime?: number | undefined;
    errorMessage?: string | undefined;
    retentionDate?: Date | undefined;
}, {
    description: string;
    action: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE";
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    userId?: string | undefined;
    tags?: string[] | undefined;
    location?: string | undefined;
    sessionId?: string | undefined;
    entityId?: string | undefined;
    entityName?: string | undefined;
    severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
    details?: Record<string, any> | undefined;
    oldValues?: Record<string, any> | undefined;
    newValues?: Record<string, any> | undefined;
    ipAddress?: string | undefined;
    userAgent?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
    responseTime?: number | undefined;
    errorMessage?: string | undefined;
    isSensitive?: boolean | undefined;
    retentionDate?: Date | undefined;
}>;
export declare const AuditLogSearchSchema: z.ZodObject<{
    query: z.ZodOptional<z.ZodString>;
    userId: z.ZodOptional<z.ZodString>;
    action: z.ZodOptional<z.ZodEnum<["CREATE", "READ", "UPDATE", "DELETE", "LOGIN", "LOGOUT", "APPROVE", "REJECT", "ASSIGN", "UNASSIGN", "EXPORT", "IMPORT", "UPLOAD", "DOWNLOAD", "SHARE", "ARCHIVE", "RESTORE", "OTHER"]>>;
    entityType: z.ZodOptional<z.ZodEnum<["USER", "TEAM", "CASE", "PARTY", "HEARING", "ORDER", "TASK", "SUBTASK", "WORKLOG", "LEAVE_REQUEST", "DOCUMENT", "SYSTEM", "CONFIGURATION", "OTHER"]>>;
    entityId: z.ZodOptional<z.ZodString>;
    severity: z.ZodOptional<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>>;
    ipAddress: z.ZodOptional<z.ZodString>;
    resource: z.ZodOptional<z.ZodString>;
    method: z.ZodOptional<z.ZodEnum<["GET", "POST", "PUT", "PATCH", "DELETE"]>>;
    statusCode: z.ZodOptional<z.ZodNumber>;
    isSensitive: z.ZodOptional<z.ZodBoolean>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    dateFrom: z.ZodOptional<z.ZodDate>;
    dateTo: z.ZodOptional<z.ZodDate>;
    limit: z.ZodDefault<z.ZodNumber>;
    offset: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    offset: number;
    query?: string | undefined;
    userId?: string | undefined;
    tags?: string[] | undefined;
    dateFrom?: Date | undefined;
    dateTo?: Date | undefined;
    action?: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE" | undefined;
    entityType?: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION" | undefined;
    entityId?: string | undefined;
    severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
    ipAddress?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
    isSensitive?: boolean | undefined;
}, {
    query?: string | undefined;
    userId?: string | undefined;
    tags?: string[] | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    dateFrom?: Date | undefined;
    dateTo?: Date | undefined;
    action?: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE" | undefined;
    entityType?: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION" | undefined;
    entityId?: string | undefined;
    severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
    ipAddress?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
    isSensitive?: boolean | undefined;
}>;
export declare const AuditLogListSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodOptional<z.ZodString>;
    action: z.ZodEnum<["CREATE", "READ", "UPDATE", "DELETE", "LOGIN", "LOGOUT", "APPROVE", "REJECT", "ASSIGN", "UNASSIGN", "EXPORT", "IMPORT", "UPLOAD", "DOWNLOAD", "SHARE", "ARCHIVE", "RESTORE", "OTHER"]>;
    entityType: z.ZodEnum<["USER", "TEAM", "CASE", "PARTY", "HEARING", "ORDER", "TASK", "SUBTASK", "WORKLOG", "LEAVE_REQUEST", "DOCUMENT", "SYSTEM", "CONFIGURATION", "OTHER"]>;
    entityId: z.ZodOptional<z.ZodString>;
    entityName: z.ZodOptional<z.ZodString>;
    severity: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
    description: z.ZodString;
    ipAddress: z.ZodOptional<z.ZodString>;
    resource: z.ZodOptional<z.ZodString>;
    method: z.ZodOptional<z.ZodEnum<["GET", "POST", "PUT", "PATCH", "DELETE"]>>;
    statusCode: z.ZodOptional<z.ZodNumber>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    description: string;
    action: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE";
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    userId?: string | undefined;
    entityId?: string | undefined;
    entityName?: string | undefined;
    ipAddress?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
}, {
    id: string;
    createdAt: Date;
    description: string;
    action: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE";
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    userId?: string | undefined;
    entityId?: string | undefined;
    entityName?: string | undefined;
    ipAddress?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
}>;
export declare const AuditLogWithUserSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodOptional<z.ZodString>;
    sessionId: z.ZodOptional<z.ZodString>;
    action: z.ZodEnum<["CREATE", "READ", "UPDATE", "DELETE", "LOGIN", "LOGOUT", "APPROVE", "REJECT", "ASSIGN", "UNASSIGN", "EXPORT", "IMPORT", "UPLOAD", "DOWNLOAD", "SHARE", "ARCHIVE", "RESTORE", "OTHER"]>;
    entityType: z.ZodEnum<["USER", "TEAM", "CASE", "PARTY", "HEARING", "ORDER", "TASK", "SUBTASK", "WORKLOG", "LEAVE_REQUEST", "DOCUMENT", "SYSTEM", "CONFIGURATION", "OTHER"]>;
    entityId: z.ZodOptional<z.ZodString>;
    entityName: z.ZodOptional<z.ZodString>;
    severity: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>>;
    description: z.ZodString;
    details: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    oldValues: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    newValues: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    ipAddress: z.ZodOptional<z.ZodString>;
    userAgent: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    resource: z.ZodOptional<z.ZodString>;
    method: z.ZodOptional<z.ZodEnum<["GET", "POST", "PUT", "PATCH", "DELETE"]>>;
    statusCode: z.ZodOptional<z.ZodNumber>;
    responseTime: z.ZodOptional<z.ZodNumber>;
    errorMessage: z.ZodOptional<z.ZodString>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isSensitive: z.ZodDefault<z.ZodBoolean>;
    retentionDate: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodDate;
} & {
    user: z.ZodOptional<z.ZodObject<{
        id: z.ZodString;
        firstName: z.ZodString;
        lastName: z.ZodString;
        email: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    description: string;
    tags: string[];
    action: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE";
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    isSensitive: boolean;
    user?: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    } | undefined;
    userId?: string | undefined;
    location?: string | undefined;
    sessionId?: string | undefined;
    entityId?: string | undefined;
    entityName?: string | undefined;
    details?: Record<string, any> | undefined;
    oldValues?: Record<string, any> | undefined;
    newValues?: Record<string, any> | undefined;
    ipAddress?: string | undefined;
    userAgent?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
    responseTime?: number | undefined;
    errorMessage?: string | undefined;
    retentionDate?: Date | undefined;
}, {
    id: string;
    createdAt: Date;
    description: string;
    action: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE";
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    user?: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    } | undefined;
    userId?: string | undefined;
    tags?: string[] | undefined;
    location?: string | undefined;
    sessionId?: string | undefined;
    entityId?: string | undefined;
    entityName?: string | undefined;
    severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
    details?: Record<string, any> | undefined;
    oldValues?: Record<string, any> | undefined;
    newValues?: Record<string, any> | undefined;
    ipAddress?: string | undefined;
    userAgent?: string | undefined;
    resource?: string | undefined;
    method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
    statusCode?: number | undefined;
    responseTime?: number | undefined;
    errorMessage?: string | undefined;
    isSensitive?: boolean | undefined;
    retentionDate?: Date | undefined;
}>;
export declare const AuditLogStatisticsSchema: z.ZodObject<{
    totalLogs: z.ZodNumber;
    byAction: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byEntityType: z.ZodRecord<z.ZodString, z.ZodNumber>;
    bySeverity: z.ZodObject<{
        low: z.ZodNumber;
        medium: z.ZodNumber;
        high: z.ZodNumber;
        critical: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        low: number;
        medium: number;
        high: number;
        critical: number;
    }, {
        low: number;
        medium: number;
        high: number;
        critical: number;
    }>;
    byStatusCode: z.ZodRecord<z.ZodString, z.ZodNumber>;
    averageResponseTime: z.ZodOptional<z.ZodNumber>;
    errorRate: z.ZodNumber;
    topUsers: z.ZodArray<z.ZodObject<{
        userId: z.ZodString;
        firstName: z.ZodString;
        lastName: z.ZodString;
        actionCount: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        firstName: string;
        lastName: string;
        userId: string;
        actionCount: number;
    }, {
        firstName: string;
        lastName: string;
        userId: string;
        actionCount: number;
    }>, "many">;
    topResources: z.ZodArray<z.ZodObject<{
        resource: z.ZodString;
        requestCount: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        resource: string;
        requestCount: number;
    }, {
        resource: string;
        requestCount: number;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    totalLogs: number;
    byAction: Record<string, number>;
    byEntityType: Record<string, number>;
    bySeverity: {
        low: number;
        medium: number;
        high: number;
        critical: number;
    };
    byStatusCode: Record<string, number>;
    errorRate: number;
    topUsers: {
        firstName: string;
        lastName: string;
        userId: string;
        actionCount: number;
    }[];
    topResources: {
        resource: string;
        requestCount: number;
    }[];
    averageResponseTime?: number | undefined;
}, {
    totalLogs: number;
    byAction: Record<string, number>;
    byEntityType: Record<string, number>;
    bySeverity: {
        low: number;
        medium: number;
        high: number;
        critical: number;
    };
    byStatusCode: Record<string, number>;
    errorRate: number;
    topUsers: {
        firstName: string;
        lastName: string;
        userId: string;
        actionCount: number;
    }[];
    topResources: {
        resource: string;
        requestCount: number;
    }[];
    averageResponseTime?: number | undefined;
}>;
export declare const AuditLogExportSchema: z.ZodObject<{
    format: z.ZodDefault<z.ZodEnum<["CSV", "JSON", "XLSX"]>>;
    dateFrom: z.ZodOptional<z.ZodDate>;
    dateTo: z.ZodOptional<z.ZodDate>;
    filters: z.ZodOptional<z.ZodObject<Omit<{
        query: z.ZodOptional<z.ZodString>;
        userId: z.ZodOptional<z.ZodString>;
        action: z.ZodOptional<z.ZodEnum<["CREATE", "READ", "UPDATE", "DELETE", "LOGIN", "LOGOUT", "APPROVE", "REJECT", "ASSIGN", "UNASSIGN", "EXPORT", "IMPORT", "UPLOAD", "DOWNLOAD", "SHARE", "ARCHIVE", "RESTORE", "OTHER"]>>;
        entityType: z.ZodOptional<z.ZodEnum<["USER", "TEAM", "CASE", "PARTY", "HEARING", "ORDER", "TASK", "SUBTASK", "WORKLOG", "LEAVE_REQUEST", "DOCUMENT", "SYSTEM", "CONFIGURATION", "OTHER"]>>;
        entityId: z.ZodOptional<z.ZodString>;
        severity: z.ZodOptional<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>>;
        ipAddress: z.ZodOptional<z.ZodString>;
        resource: z.ZodOptional<z.ZodString>;
        method: z.ZodOptional<z.ZodEnum<["GET", "POST", "PUT", "PATCH", "DELETE"]>>;
        statusCode: z.ZodOptional<z.ZodNumber>;
        isSensitive: z.ZodOptional<z.ZodBoolean>;
        tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        dateFrom: z.ZodOptional<z.ZodDate>;
        dateTo: z.ZodOptional<z.ZodDate>;
        limit: z.ZodDefault<z.ZodNumber>;
        offset: z.ZodDefault<z.ZodNumber>;
    }, "limit" | "offset">, "strip", z.ZodTypeAny, {
        query?: string | undefined;
        userId?: string | undefined;
        tags?: string[] | undefined;
        dateFrom?: Date | undefined;
        dateTo?: Date | undefined;
        action?: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE" | undefined;
        entityType?: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION" | undefined;
        entityId?: string | undefined;
        severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
        ipAddress?: string | undefined;
        resource?: string | undefined;
        method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
        statusCode?: number | undefined;
        isSensitive?: boolean | undefined;
    }, {
        query?: string | undefined;
        userId?: string | undefined;
        tags?: string[] | undefined;
        dateFrom?: Date | undefined;
        dateTo?: Date | undefined;
        action?: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE" | undefined;
        entityType?: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION" | undefined;
        entityId?: string | undefined;
        severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
        ipAddress?: string | undefined;
        resource?: string | undefined;
        method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
        statusCode?: number | undefined;
        isSensitive?: boolean | undefined;
    }>>;
    includeSensitive: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    format: "CSV" | "JSON" | "XLSX";
    includeSensitive: boolean;
    dateFrom?: Date | undefined;
    dateTo?: Date | undefined;
    filters?: {
        query?: string | undefined;
        userId?: string | undefined;
        tags?: string[] | undefined;
        dateFrom?: Date | undefined;
        dateTo?: Date | undefined;
        action?: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE" | undefined;
        entityType?: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION" | undefined;
        entityId?: string | undefined;
        severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
        ipAddress?: string | undefined;
        resource?: string | undefined;
        method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
        statusCode?: number | undefined;
        isSensitive?: boolean | undefined;
    } | undefined;
}, {
    dateFrom?: Date | undefined;
    dateTo?: Date | undefined;
    format?: "CSV" | "JSON" | "XLSX" | undefined;
    filters?: {
        query?: string | undefined;
        userId?: string | undefined;
        tags?: string[] | undefined;
        dateFrom?: Date | undefined;
        dateTo?: Date | undefined;
        action?: "OTHER" | "CREATE" | "READ" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT" | "APPROVE" | "REJECT" | "ASSIGN" | "UNASSIGN" | "EXPORT" | "IMPORT" | "UPLOAD" | "DOWNLOAD" | "SHARE" | "ARCHIVE" | "RESTORE" | undefined;
        entityType?: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION" | undefined;
        entityId?: string | undefined;
        severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | undefined;
        ipAddress?: string | undefined;
        resource?: string | undefined;
        method?: "DELETE" | "GET" | "POST" | "PUT" | "PATCH" | undefined;
        statusCode?: number | undefined;
        isSensitive?: boolean | undefined;
    } | undefined;
    includeSensitive?: boolean | undefined;
}>;
export declare const AuditLogRetentionSchema: z.ZodObject<{
    entityType: z.ZodEnum<["USER", "TEAM", "CASE", "PARTY", "HEARING", "ORDER", "TASK", "SUBTASK", "WORKLOG", "LEAVE_REQUEST", "DOCUMENT", "SYSTEM", "CONFIGURATION", "OTHER"]>;
    retentionDays: z.ZodNumber;
    isActive: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    isActive: boolean;
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    retentionDays: number;
}, {
    entityType: "OTHER" | "CASE" | "USER" | "TEAM" | "PARTY" | "HEARING" | "ORDER" | "TASK" | "SUBTASK" | "WORKLOG" | "LEAVE_REQUEST" | "DOCUMENT" | "SYSTEM" | "CONFIGURATION";
    retentionDays: number;
    isActive?: boolean | undefined;
}>;
export type AuditLog = z.infer<typeof AuditLogSchema>;
export type CreateAuditLog = z.infer<typeof CreateAuditLogSchema>;
export type AuditLogSearch = z.infer<typeof AuditLogSearchSchema>;
export type AuditLogList = z.infer<typeof AuditLogListSchema>;
export type AuditLogWithUser = z.infer<typeof AuditLogWithUserSchema>;
export type AuditLogStatistics = z.infer<typeof AuditLogStatisticsSchema>;
export type AuditLogExport = z.infer<typeof AuditLogExportSchema>;
export type AuditLogRetention = z.infer<typeof AuditLogRetentionSchema>;
//# sourceMappingURL=audit-log.d.ts.map