import { z } from 'zod';
export declare const CaseStatusSchema: z.ZodEnum<["OPEN", "IN_PROGRESS", "CLOSED", "ARCHIVED", "SUSPENDED"]>;
export type CaseStatus = z.infer<typeof CaseStatusSchema>;
export declare const CasePrioritySchema: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>;
export type CasePriority = z.infer<typeof CasePrioritySchema>;
export declare const CaseTypeSchema: z.ZodEnum<["CIVIL", "CRIMINAL", "FAMILY", "CORPORATE", "INTELLECTUAL_PROPERTY", "LABOR", "TAX", "REAL_ESTATE", "BANKING", "INSURANCE", "OTHER"]>;
export type CaseType = z.infer<typeof CaseTypeSchema>;
export declare const CaseSchema: z.ZodObject<{
    id: z.ZodString;
    caseNumber: z.ZodString;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["OPEN", "IN_PROGRESS", "CLOSED", "ARCHIVED", "SUSPENDED"]>>;
    priority: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    type: z.ZodDefault<z.ZodEnum<["CIVIL", "CRIMINAL", "FAMILY", "CORPORATE", "INTELLECTUAL_PROPERTY", "LABOR", "TAX", "REAL_ESTATE", "BANKING", "INSURANCE", "OTHER"]>>;
    clientId: z.ZodString;
    assignedLawyerId: z.ZodOptional<z.ZodString>;
    teamId: z.ZodOptional<z.ZodString>;
    courtName: z.ZodOptional<z.ZodString>;
    courtLocation: z.ZodOptional<z.ZodString>;
    caseValue: z.ZodOptional<z.ZodNumber>;
    currency: z.ZodDefault<z.ZodString>;
    filingDate: z.ZodOptional<z.ZodDate>;
    expectedCompletionDate: z.ZodOptional<z.ZodDate>;
    actualCompletionDate: z.ZodOptional<z.ZodDate>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isConfidential: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED";
    type: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER";
    createdAt: Date;
    updatedAt: Date;
    caseNumber: string;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    clientId: string;
    currency: string;
    tags: string[];
    isConfidential: boolean;
    description?: string | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    courtLocation?: string | undefined;
    caseValue?: number | undefined;
    filingDate?: Date | undefined;
    expectedCompletionDate?: Date | undefined;
    actualCompletionDate?: Date | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    caseNumber: string;
    title: string;
    clientId: string;
    status?: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED" | undefined;
    type?: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER" | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    courtLocation?: string | undefined;
    caseValue?: number | undefined;
    currency?: string | undefined;
    filingDate?: Date | undefined;
    expectedCompletionDate?: Date | undefined;
    actualCompletionDate?: Date | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
}>;
export declare const CreateCaseSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    caseNumber: z.ZodString;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["OPEN", "IN_PROGRESS", "CLOSED", "ARCHIVED", "SUSPENDED"]>>;
    priority: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    type: z.ZodDefault<z.ZodEnum<["CIVIL", "CRIMINAL", "FAMILY", "CORPORATE", "INTELLECTUAL_PROPERTY", "LABOR", "TAX", "REAL_ESTATE", "BANKING", "INSURANCE", "OTHER"]>>;
    clientId: z.ZodString;
    assignedLawyerId: z.ZodOptional<z.ZodString>;
    teamId: z.ZodOptional<z.ZodString>;
    courtName: z.ZodOptional<z.ZodString>;
    courtLocation: z.ZodOptional<z.ZodString>;
    caseValue: z.ZodOptional<z.ZodNumber>;
    currency: z.ZodDefault<z.ZodString>;
    filingDate: z.ZodOptional<z.ZodDate>;
    expectedCompletionDate: z.ZodOptional<z.ZodDate>;
    actualCompletionDate: z.ZodOptional<z.ZodDate>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isConfidential: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "id" | "createdAt" | "updatedAt" | "actualCompletionDate">, "strip", z.ZodTypeAny, {
    status: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED";
    type: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER";
    caseNumber: string;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    clientId: string;
    currency: string;
    tags: string[];
    isConfidential: boolean;
    description?: string | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    courtLocation?: string | undefined;
    caseValue?: number | undefined;
    filingDate?: Date | undefined;
    expectedCompletionDate?: Date | undefined;
}, {
    caseNumber: string;
    title: string;
    clientId: string;
    status?: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED" | undefined;
    type?: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER" | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    courtLocation?: string | undefined;
    caseValue?: number | undefined;
    currency?: string | undefined;
    filingDate?: Date | undefined;
    expectedCompletionDate?: Date | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
}>;
export declare const UpdateCaseSchema: z.ZodObject<{
    status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["OPEN", "IN_PROGRESS", "CLOSED", "ARCHIVED", "SUSPENDED"]>>>;
    type: z.ZodOptional<z.ZodDefault<z.ZodEnum<["CIVIL", "CRIMINAL", "FAMILY", "CORPORATE", "INTELLECTUAL_PROPERTY", "LABOR", "TAX", "REAL_ESTATE", "BANKING", "INSURANCE", "OTHER"]>>>;
    caseNumber: z.ZodOptional<z.ZodString>;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    priority: z.ZodOptional<z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>>;
    clientId: z.ZodOptional<z.ZodString>;
    assignedLawyerId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    teamId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    courtName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    courtLocation: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    caseValue: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    currency: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    filingDate: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    expectedCompletionDate: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    tags: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    isConfidential: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
}, "strip", z.ZodTypeAny, {
    status?: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED" | undefined;
    type?: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER" | undefined;
    caseNumber?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    clientId?: string | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    courtLocation?: string | undefined;
    caseValue?: number | undefined;
    currency?: string | undefined;
    filingDate?: Date | undefined;
    expectedCompletionDate?: Date | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
}, {
    status?: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED" | undefined;
    type?: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER" | undefined;
    caseNumber?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    clientId?: string | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    courtLocation?: string | undefined;
    caseValue?: number | undefined;
    currency?: string | undefined;
    filingDate?: Date | undefined;
    expectedCompletionDate?: Date | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
}>;
export declare const CaseSearchSchema: z.ZodObject<{
    query: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodEnum<["OPEN", "IN_PROGRESS", "CLOSED", "ARCHIVED", "SUSPENDED"]>>;
    priority: z.ZodOptional<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    type: z.ZodOptional<z.ZodEnum<["CIVIL", "CRIMINAL", "FAMILY", "CORPORATE", "INTELLECTUAL_PROPERTY", "LABOR", "TAX", "REAL_ESTATE", "BANKING", "INSURANCE", "OTHER"]>>;
    clientId: z.ZodOptional<z.ZodString>;
    assignedLawyerId: z.ZodOptional<z.ZodString>;
    teamId: z.ZodOptional<z.ZodString>;
    courtName: z.ZodOptional<z.ZodString>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    filingDateFrom: z.ZodOptional<z.ZodDate>;
    filingDateTo: z.ZodOptional<z.ZodDate>;
    isConfidential: z.ZodOptional<z.ZodBoolean>;
    limit: z.ZodDefault<z.ZodNumber>;
    offset: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    offset: number;
    query?: string | undefined;
    status?: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED" | undefined;
    type?: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER" | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    clientId?: string | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    filingDateFrom?: Date | undefined;
    filingDateTo?: Date | undefined;
}, {
    query?: string | undefined;
    status?: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED" | undefined;
    type?: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER" | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    clientId?: string | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    filingDateFrom?: Date | undefined;
    filingDateTo?: Date | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
}>;
export declare const CaseListSchema: z.ZodObject<{
    id: z.ZodString;
    caseNumber: z.ZodString;
    title: z.ZodString;
    status: z.ZodEnum<["OPEN", "IN_PROGRESS", "CLOSED", "ARCHIVED", "SUSPENDED"]>;
    priority: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>;
    type: z.ZodEnum<["CIVIL", "CRIMINAL", "FAMILY", "CORPORATE", "INTELLECTUAL_PROPERTY", "LABOR", "TAX", "REAL_ESTATE", "BANKING", "INSURANCE", "OTHER"]>;
    clientId: z.ZodString;
    assignedLawyerId: z.ZodOptional<z.ZodString>;
    courtName: z.ZodOptional<z.ZodString>;
    filingDate: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED";
    type: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER";
    createdAt: Date;
    caseNumber: string;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    clientId: string;
    assignedLawyerId?: string | undefined;
    courtName?: string | undefined;
    filingDate?: Date | undefined;
}, {
    id: string;
    status: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED";
    type: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER";
    createdAt: Date;
    caseNumber: string;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    clientId: string;
    assignedLawyerId?: string | undefined;
    courtName?: string | undefined;
    filingDate?: Date | undefined;
}>;
export declare const CaseWithRelationsSchema: z.ZodObject<{
    id: z.ZodString;
    caseNumber: z.ZodString;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["OPEN", "IN_PROGRESS", "CLOSED", "ARCHIVED", "SUSPENDED"]>>;
    priority: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    type: z.ZodDefault<z.ZodEnum<["CIVIL", "CRIMINAL", "FAMILY", "CORPORATE", "INTELLECTUAL_PROPERTY", "LABOR", "TAX", "REAL_ESTATE", "BANKING", "INSURANCE", "OTHER"]>>;
    clientId: z.ZodString;
    assignedLawyerId: z.ZodOptional<z.ZodString>;
    teamId: z.ZodOptional<z.ZodString>;
    courtName: z.ZodOptional<z.ZodString>;
    courtLocation: z.ZodOptional<z.ZodString>;
    caseValue: z.ZodOptional<z.ZodNumber>;
    currency: z.ZodDefault<z.ZodString>;
    filingDate: z.ZodOptional<z.ZodDate>;
    expectedCompletionDate: z.ZodOptional<z.ZodDate>;
    actualCompletionDate: z.ZodOptional<z.ZodDate>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isConfidential: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
} & {
    client: z.ZodObject<{
        id: z.ZodString;
        firstName: z.ZodString;
        lastName: z.ZodString;
        email: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }>;
    assignedLawyer: z.ZodOptional<z.ZodObject<{
        id: z.ZodString;
        firstName: z.ZodString;
        lastName: z.ZodString;
        email: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }>>;
    team: z.ZodOptional<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        name: string;
    }, {
        id: string;
        name: string;
    }>>;
}, "strip", z.ZodTypeAny, {
    client: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    };
    id: string;
    status: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED";
    type: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER";
    createdAt: Date;
    updatedAt: Date;
    caseNumber: string;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    clientId: string;
    currency: string;
    tags: string[];
    isConfidential: boolean;
    team?: {
        id: string;
        name: string;
    } | undefined;
    description?: string | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    courtLocation?: string | undefined;
    caseValue?: number | undefined;
    filingDate?: Date | undefined;
    expectedCompletionDate?: Date | undefined;
    actualCompletionDate?: Date | undefined;
    assignedLawyer?: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    } | undefined;
}, {
    client: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    };
    id: string;
    createdAt: Date;
    updatedAt: Date;
    caseNumber: string;
    title: string;
    clientId: string;
    team?: {
        id: string;
        name: string;
    } | undefined;
    status?: "SUSPENDED" | "ARCHIVED" | "OPEN" | "IN_PROGRESS" | "CLOSED" | undefined;
    type?: "CIVIL" | "CRIMINAL" | "FAMILY" | "CORPORATE" | "INTELLECTUAL_PROPERTY" | "LABOR" | "TAX" | "REAL_ESTATE" | "BANKING" | "INSURANCE" | "OTHER" | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    assignedLawyerId?: string | undefined;
    teamId?: string | undefined;
    courtName?: string | undefined;
    courtLocation?: string | undefined;
    caseValue?: number | undefined;
    currency?: string | undefined;
    filingDate?: Date | undefined;
    expectedCompletionDate?: Date | undefined;
    actualCompletionDate?: Date | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    assignedLawyer?: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    } | undefined;
}>;
export declare const CaseStatisticsSchema: z.ZodObject<{
    total: z.ZodNumber;
    open: z.ZodNumber;
    inProgress: z.ZodNumber;
    closed: z.ZodNumber;
    archived: z.ZodNumber;
    byPriority: z.ZodObject<{
        low: z.ZodNumber;
        medium: z.ZodNumber;
        high: z.ZodNumber;
        urgent: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        low: number;
        medium: number;
        high: number;
        urgent: number;
    }, {
        low: number;
        medium: number;
        high: number;
        urgent: number;
    }>;
    byType: z.ZodRecord<z.ZodString, z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    open: number;
    closed: number;
    archived: number;
    total: number;
    inProgress: number;
    byPriority: {
        low: number;
        medium: number;
        high: number;
        urgent: number;
    };
    byType: Record<string, number>;
}, {
    open: number;
    closed: number;
    archived: number;
    total: number;
    inProgress: number;
    byPriority: {
        low: number;
        medium: number;
        high: number;
        urgent: number;
    };
    byType: Record<string, number>;
}>;
export type Case = z.infer<typeof CaseSchema>;
export type CreateCase = z.infer<typeof CreateCaseSchema>;
export type UpdateCase = z.infer<typeof UpdateCaseSchema>;
export type CaseSearch = z.infer<typeof CaseSearchSchema>;
export type CaseList = z.infer<typeof CaseListSchema>;
export type CaseWithRelations = z.infer<typeof CaseWithRelationsSchema>;
export type CaseStatistics = z.infer<typeof CaseStatisticsSchema>;
//# sourceMappingURL=case.d.ts.map