import { z } from 'zod';
export declare const LeaveTypeSchema: z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>;
export type LeaveType = z.infer<typeof LeaveTypeSchema>;
export declare const LeaveStatusSchema: z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>;
export type LeaveStatus = z.infer<typeof LeaveStatusSchema>;
export declare const LeaveDurationSchema: z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>;
export type LeaveDuration = z.infer<typeof LeaveDurationSchema>;
export declare const LeaveRequestSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>>;
    status: z.ZodDefault<z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>>;
    duration: z.ZodDefault<z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>>;
    startDate: z.ZodDate;
    endDate: z.ZodDate;
    startTime: z.ZodOptional<z.ZodString>;
    endTime: z.ZodOptional<z.ZodString>;
    totalDays: z.ZodNumber;
    reason: z.ZodString;
    medicalCertificate: z.ZodOptional<z.ZodString>;
    emergencyContact: z.ZodOptional<z.ZodString>;
    emergencyPhone: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    appliedBy: z.ZodString;
    appliedAt: z.ZodDate;
    approvedBy: z.ZodOptional<z.ZodString>;
    approvedAt: z.ZodOptional<z.ZodDate>;
    rejectedBy: z.ZodOptional<z.ZodString>;
    rejectedAt: z.ZodOptional<z.ZodDate>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    cancelledBy: z.ZodOptional<z.ZodString>;
    cancelledAt: z.ZodOptional<z.ZodDate>;
    cancellationReason: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    isEmergency: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
    type: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    duration: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY";
    attachments: string[];
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedBy: string;
    appliedAt: Date;
    isEmergency: boolean;
    notes?: string | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    rejectedBy?: string | undefined;
    rejectedAt?: Date | undefined;
    cancelledBy?: string | undefined;
    cancelledAt?: Date | undefined;
    cancellationReason?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedBy: string;
    appliedAt: Date;
    status?: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED" | undefined;
    type?: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE" | undefined;
    notes?: string | undefined;
    duration?: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY" | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    attachments?: string[] | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    rejectedBy?: string | undefined;
    rejectedAt?: Date | undefined;
    cancelledBy?: string | undefined;
    cancelledAt?: Date | undefined;
    cancellationReason?: string | undefined;
    isEmergency?: boolean | undefined;
}>;
export declare const CreateLeaveRequestSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    userId: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>>;
    status: z.ZodDefault<z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>>;
    duration: z.ZodDefault<z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>>;
    startDate: z.ZodDate;
    endDate: z.ZodDate;
    startTime: z.ZodOptional<z.ZodString>;
    endTime: z.ZodOptional<z.ZodString>;
    totalDays: z.ZodNumber;
    reason: z.ZodString;
    medicalCertificate: z.ZodOptional<z.ZodString>;
    emergencyContact: z.ZodOptional<z.ZodString>;
    emergencyPhone: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    appliedBy: z.ZodString;
    appliedAt: z.ZodDate;
    approvedBy: z.ZodOptional<z.ZodString>;
    approvedAt: z.ZodOptional<z.ZodDate>;
    rejectedBy: z.ZodOptional<z.ZodString>;
    rejectedAt: z.ZodOptional<z.ZodDate>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    cancelledBy: z.ZodOptional<z.ZodString>;
    cancelledAt: z.ZodOptional<z.ZodDate>;
    cancellationReason: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    isEmergency: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "id" | "createdAt" | "updatedAt" | "approvedAt" | "appliedAt" | "rejectedAt" | "cancelledAt">, "strip", z.ZodTypeAny, {
    status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
    type: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    userId: string;
    duration: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY";
    attachments: string[];
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedBy: string;
    isEmergency: boolean;
    notes?: string | undefined;
    approvedBy?: string | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    rejectedBy?: string | undefined;
    cancelledBy?: string | undefined;
    cancellationReason?: string | undefined;
}, {
    userId: string;
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedBy: string;
    status?: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED" | undefined;
    type?: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE" | undefined;
    notes?: string | undefined;
    duration?: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY" | undefined;
    approvedBy?: string | undefined;
    attachments?: string[] | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    rejectedBy?: string | undefined;
    cancelledBy?: string | undefined;
    cancellationReason?: string | undefined;
    isEmergency?: boolean | undefined;
}>;
export declare const UpdateLeaveRequestSchema: z.ZodObject<{
    status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>>>;
    type: z.ZodOptional<z.ZodDefault<z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>>>;
    userId: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    duration: z.ZodOptional<z.ZodDefault<z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>>>;
    approvedBy: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    attachments: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    endDate: z.ZodOptional<z.ZodDate>;
    startTime: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    endTime: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    rejectionReason: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    startDate: z.ZodOptional<z.ZodDate>;
    totalDays: z.ZodOptional<z.ZodNumber>;
    reason: z.ZodOptional<z.ZodString>;
    medicalCertificate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    emergencyContact: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    emergencyPhone: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    appliedBy: z.ZodOptional<z.ZodString>;
    rejectedBy: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cancelledBy: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cancellationReason: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    isEmergency: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
}, "strip", z.ZodTypeAny, {
    status?: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED" | undefined;
    type?: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE" | undefined;
    userId?: string | undefined;
    notes?: string | undefined;
    duration?: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY" | undefined;
    approvedBy?: string | undefined;
    attachments?: string[] | undefined;
    endDate?: Date | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    startDate?: Date | undefined;
    totalDays?: number | undefined;
    reason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    appliedBy?: string | undefined;
    rejectedBy?: string | undefined;
    cancelledBy?: string | undefined;
    cancellationReason?: string | undefined;
    isEmergency?: boolean | undefined;
}, {
    status?: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED" | undefined;
    type?: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE" | undefined;
    userId?: string | undefined;
    notes?: string | undefined;
    duration?: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY" | undefined;
    approvedBy?: string | undefined;
    attachments?: string[] | undefined;
    endDate?: Date | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    startDate?: Date | undefined;
    totalDays?: number | undefined;
    reason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    appliedBy?: string | undefined;
    rejectedBy?: string | undefined;
    cancelledBy?: string | undefined;
    cancellationReason?: string | undefined;
    isEmergency?: boolean | undefined;
}>;
export declare const LeaveRequestSearchSchema: z.ZodObject<{
    query: z.ZodOptional<z.ZodString>;
    userId: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>>;
    status: z.ZodOptional<z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>>;
    duration: z.ZodOptional<z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>>;
    startDateFrom: z.ZodOptional<z.ZodDate>;
    startDateTo: z.ZodOptional<z.ZodDate>;
    endDateFrom: z.ZodOptional<z.ZodDate>;
    endDateTo: z.ZodOptional<z.ZodDate>;
    appliedBy: z.ZodOptional<z.ZodString>;
    approvedBy: z.ZodOptional<z.ZodString>;
    isEmergency: z.ZodOptional<z.ZodBoolean>;
    limit: z.ZodDefault<z.ZodNumber>;
    offset: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    offset: number;
    query?: string | undefined;
    status?: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED" | undefined;
    type?: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE" | undefined;
    userId?: string | undefined;
    duration?: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY" | undefined;
    approvedBy?: string | undefined;
    appliedBy?: string | undefined;
    isEmergency?: boolean | undefined;
    startDateFrom?: Date | undefined;
    startDateTo?: Date | undefined;
    endDateFrom?: Date | undefined;
    endDateTo?: Date | undefined;
}, {
    query?: string | undefined;
    status?: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED" | undefined;
    type?: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE" | undefined;
    userId?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    duration?: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY" | undefined;
    approvedBy?: string | undefined;
    appliedBy?: string | undefined;
    isEmergency?: boolean | undefined;
    startDateFrom?: Date | undefined;
    startDateTo?: Date | undefined;
    endDateFrom?: Date | undefined;
    endDateTo?: Date | undefined;
}>;
export declare const LeaveRequestListSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    type: z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>;
    status: z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>;
    duration: z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>;
    startDate: z.ZodDate;
    endDate: z.ZodDate;
    totalDays: z.ZodNumber;
    reason: z.ZodString;
    appliedAt: z.ZodDate;
    approvedAt: z.ZodOptional<z.ZodDate>;
    rejectedAt: z.ZodOptional<z.ZodDate>;
    isEmergency: z.ZodBoolean;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
    type: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    userId: string;
    duration: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY";
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedAt: Date;
    isEmergency: boolean;
    approvedAt?: Date | undefined;
    rejectedAt?: Date | undefined;
}, {
    id: string;
    status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
    type: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    userId: string;
    duration: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY";
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedAt: Date;
    isEmergency: boolean;
    approvedAt?: Date | undefined;
    rejectedAt?: Date | undefined;
}>;
export declare const LeaveRequestWithUserSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>>;
    status: z.ZodDefault<z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>>;
    duration: z.ZodDefault<z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>>;
    startDate: z.ZodDate;
    endDate: z.ZodDate;
    startTime: z.ZodOptional<z.ZodString>;
    endTime: z.ZodOptional<z.ZodString>;
    totalDays: z.ZodNumber;
    reason: z.ZodString;
    medicalCertificate: z.ZodOptional<z.ZodString>;
    emergencyContact: z.ZodOptional<z.ZodString>;
    emergencyPhone: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    appliedBy: z.ZodString;
    appliedAt: z.ZodDate;
    approvedBy: z.ZodOptional<z.ZodString>;
    approvedAt: z.ZodOptional<z.ZodDate>;
    rejectedBy: z.ZodOptional<z.ZodString>;
    rejectedAt: z.ZodOptional<z.ZodDate>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    cancelledBy: z.ZodOptional<z.ZodString>;
    cancelledAt: z.ZodOptional<z.ZodDate>;
    cancellationReason: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    isEmergency: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
} & {
    user: z.ZodObject<{
        id: z.ZodString;
        firstName: z.ZodString;
        lastName: z.ZodString;
        email: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }>;
}, "strip", z.ZodTypeAny, {
    user: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    };
    id: string;
    status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
    type: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    duration: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY";
    attachments: string[];
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedBy: string;
    appliedAt: Date;
    isEmergency: boolean;
    notes?: string | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    rejectedBy?: string | undefined;
    rejectedAt?: Date | undefined;
    cancelledBy?: string | undefined;
    cancelledAt?: Date | undefined;
    cancellationReason?: string | undefined;
}, {
    user: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    };
    id: string;
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedBy: string;
    appliedAt: Date;
    status?: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED" | undefined;
    type?: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE" | undefined;
    notes?: string | undefined;
    duration?: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY" | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    attachments?: string[] | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    rejectedBy?: string | undefined;
    rejectedAt?: Date | undefined;
    cancelledBy?: string | undefined;
    cancelledAt?: Date | undefined;
    cancellationReason?: string | undefined;
    isEmergency?: boolean | undefined;
}>;
export declare const LeaveRequestWithApproverSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>>;
    status: z.ZodDefault<z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>>;
    duration: z.ZodDefault<z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>>;
    startDate: z.ZodDate;
    endDate: z.ZodDate;
    startTime: z.ZodOptional<z.ZodString>;
    endTime: z.ZodOptional<z.ZodString>;
    totalDays: z.ZodNumber;
    reason: z.ZodString;
    medicalCertificate: z.ZodOptional<z.ZodString>;
    emergencyContact: z.ZodOptional<z.ZodString>;
    emergencyPhone: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    appliedBy: z.ZodString;
    appliedAt: z.ZodDate;
    approvedBy: z.ZodOptional<z.ZodString>;
    approvedAt: z.ZodOptional<z.ZodDate>;
    rejectedBy: z.ZodOptional<z.ZodString>;
    rejectedAt: z.ZodOptional<z.ZodDate>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    cancelledBy: z.ZodOptional<z.ZodString>;
    cancelledAt: z.ZodOptional<z.ZodDate>;
    cancellationReason: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    isEmergency: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
} & {
    approver: z.ZodOptional<z.ZodObject<{
        id: z.ZodString;
        firstName: z.ZodString;
        lastName: z.ZodString;
        email: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
    type: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    duration: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY";
    attachments: string[];
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedBy: string;
    appliedAt: Date;
    isEmergency: boolean;
    notes?: string | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    rejectedBy?: string | undefined;
    rejectedAt?: Date | undefined;
    cancelledBy?: string | undefined;
    cancelledAt?: Date | undefined;
    cancellationReason?: string | undefined;
    approver?: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    } | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    endDate: Date;
    startDate: Date;
    totalDays: number;
    reason: string;
    appliedBy: string;
    appliedAt: Date;
    status?: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED" | undefined;
    type?: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE" | undefined;
    notes?: string | undefined;
    duration?: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY" | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    attachments?: string[] | undefined;
    startTime?: string | undefined;
    endTime?: string | undefined;
    rejectionReason?: string | undefined;
    medicalCertificate?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    rejectedBy?: string | undefined;
    rejectedAt?: Date | undefined;
    cancelledBy?: string | undefined;
    cancelledAt?: Date | undefined;
    cancellationReason?: string | undefined;
    isEmergency?: boolean | undefined;
    approver?: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    } | undefined;
}>;
export declare const LeaveRequestApprovalSchema: z.ZodObject<{
    leaveRequestId: z.ZodString;
    status: z.ZodEnum<["APPROVED", "REJECTED"]>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "APPROVED" | "REJECTED";
    leaveRequestId: string;
    notes?: string | undefined;
}, {
    status: "APPROVED" | "REJECTED";
    leaveRequestId: string;
    notes?: string | undefined;
}>;
export declare const LeaveRequestCancellationSchema: z.ZodObject<{
    leaveRequestId: z.ZodString;
    reason: z.ZodString;
}, "strip", z.ZodTypeAny, {
    reason: string;
    leaveRequestId: string;
}, {
    reason: string;
    leaveRequestId: string;
}>;
export declare const LeaveBalanceSchema: z.ZodObject<{
    userId: z.ZodString;
    leaveType: z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>;
    totalDays: z.ZodNumber;
    usedDays: z.ZodNumber;
    remainingDays: z.ZodNumber;
    pendingDays: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    userId: string;
    totalDays: number;
    leaveType: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    usedDays: number;
    remainingDays: number;
    pendingDays: number;
}, {
    userId: string;
    totalDays: number;
    leaveType: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    usedDays: number;
    remainingDays: number;
    pendingDays: number;
}>;
export declare const LeaveCalendarSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    type: z.ZodEnum<["SICK_LEAVE", "ANNUAL_LEAVE", "CASUAL_LEAVE", "MATERNITY_LEAVE", "PATERNITY_LEAVE", "BEREAVEMENT_LEAVE", "COMPENSATORY_LEAVE", "SABBATICAL", "UNPAID_LEAVE", "OTHER"]>;
    status: z.ZodEnum<["PENDING", "APPROVED", "REJECTED", "CANCELLED"]>;
    startDate: z.ZodDate;
    endDate: z.ZodDate;
    duration: z.ZodEnum<["FULL_DAY", "HALF_DAY_MORNING", "HALF_DAY_EVENING", "HOURLY"]>;
    firstName: z.ZodString;
    lastName: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    firstName: string;
    lastName: string;
    status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
    type: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    userId: string;
    duration: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY";
    endDate: Date;
    startDate: Date;
}, {
    id: string;
    firstName: string;
    lastName: string;
    status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
    type: "OTHER" | "SICK_LEAVE" | "ANNUAL_LEAVE" | "CASUAL_LEAVE" | "MATERNITY_LEAVE" | "PATERNITY_LEAVE" | "BEREAVEMENT_LEAVE" | "COMPENSATORY_LEAVE" | "SABBATICAL" | "UNPAID_LEAVE";
    userId: string;
    duration: "FULL_DAY" | "HALF_DAY_MORNING" | "HALF_DAY_EVENING" | "HOURLY";
    endDate: Date;
    startDate: Date;
}>;
export declare const LeaveStatisticsSchema: z.ZodObject<{
    totalRequests: z.ZodNumber;
    pending: z.ZodNumber;
    approved: z.ZodNumber;
    rejected: z.ZodNumber;
    cancelled: z.ZodNumber;
    byType: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byDuration: z.ZodObject<{
        fullDay: z.ZodNumber;
        halfDayMorning: z.ZodNumber;
        halfDayEvening: z.ZodNumber;
        hourly: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        fullDay: number;
        halfDayMorning: number;
        halfDayEvening: number;
        hourly: number;
    }, {
        fullDay: number;
        halfDayMorning: number;
        halfDayEvening: number;
        hourly: number;
    }>;
    averageDaysPerRequest: z.ZodNumber;
    mostCommonLeaveType: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    byType: Record<string, number>;
    cancelled: number;
    pending: number;
    approved: number;
    rejected: number;
    totalRequests: number;
    byDuration: {
        fullDay: number;
        halfDayMorning: number;
        halfDayEvening: number;
        hourly: number;
    };
    averageDaysPerRequest: number;
    mostCommonLeaveType?: string | undefined;
}, {
    byType: Record<string, number>;
    cancelled: number;
    pending: number;
    approved: number;
    rejected: number;
    totalRequests: number;
    byDuration: {
        fullDay: number;
        halfDayMorning: number;
        halfDayEvening: number;
        hourly: number;
    };
    averageDaysPerRequest: number;
    mostCommonLeaveType?: string | undefined;
}>;
export type LeaveRequest = z.infer<typeof LeaveRequestSchema>;
export type CreateLeaveRequest = z.infer<typeof CreateLeaveRequestSchema>;
export type UpdateLeaveRequest = z.infer<typeof UpdateLeaveRequestSchema>;
export type LeaveRequestSearch = z.infer<typeof LeaveRequestSearchSchema>;
export type LeaveRequestList = z.infer<typeof LeaveRequestListSchema>;
export type LeaveRequestWithUser = z.infer<typeof LeaveRequestWithUserSchema>;
export type LeaveRequestWithApprover = z.infer<typeof LeaveRequestWithApproverSchema>;
export type LeaveRequestApproval = z.infer<typeof LeaveRequestApprovalSchema>;
export type LeaveRequestCancellation = z.infer<typeof LeaveRequestCancellationSchema>;
export type LeaveBalance = z.infer<typeof LeaveBalanceSchema>;
export type LeaveCalendar = z.infer<typeof LeaveCalendarSchema>;
export type LeaveStatistics = z.infer<typeof LeaveStatisticsSchema>;
//# sourceMappingURL=leave-request.d.ts.map