import { z } from 'zod';
export declare const OrderStatusSchema: z.ZodEnum<["DRAFT", "PENDING", "APPROVED", "REJECTED", "EXECUTED", "CANCELLED"]>;
export type OrderStatus = z.infer<typeof OrderStatusSchema>;
export declare const OrderTypeSchema: z.ZodEnum<["INTERIM_ORDER", "FINAL_ORDER", "EXECUTION_ORDER", "STAY_ORDER", "INJUNCTION", "DECREE", "AWARD", "SETTLEMENT", "OTHER"]>;
export type OrderType = z.infer<typeof OrderTypeSchema>;
export declare const OrderPrioritySchema: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>;
export type OrderPriority = z.infer<typeof OrderPrioritySchema>;
export declare const OrderSchema: z.ZodObject<{
    id: z.ZodString;
    caseId: z.ZodString;
    orderNumber: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["INTERIM_ORDER", "FINAL_ORDER", "EXECUTION_ORDER", "STAY_ORDER", "INJUNCTION", "DECREE", "AWARD", "SETTLEMENT", "OTHER"]>>;
    status: z.ZodDefault<z.ZodEnum<["DRAFT", "PENDING", "APPROVED", "REJECTED", "EXECUTED", "CANCELLED"]>>;
    priority: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    courtName: z.ZodString;
    judgeName: z.ZodOptional<z.ZodString>;
    orderDate: z.ZodOptional<z.ZodDate>;
    effectiveDate: z.ZodOptional<z.ZodDate>;
    expiryDate: z.ZodOptional<z.ZodDate>;
    createdBy: z.ZodString;
    approvedBy: z.ZodOptional<z.ZodString>;
    approvedAt: z.ZodOptional<z.ZodDate>;
    executedBy: z.ZodOptional<z.ZodString>;
    executedAt: z.ZodOptional<z.ZodDate>;
    executionNotes: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isConfidential: z.ZodDefault<z.ZodBoolean>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED";
    type: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT";
    createdAt: Date;
    updatedAt: Date;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    caseId: string;
    courtName: string;
    tags: string[];
    isConfidential: boolean;
    orderNumber: string;
    content: string;
    createdBy: string;
    attachments: string[];
    description?: string | undefined;
    judgeName?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    executedBy?: string | undefined;
    executedAt?: Date | undefined;
    executionNotes?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    caseId: string;
    courtName: string;
    orderNumber: string;
    content: string;
    createdBy: string;
    status?: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED" | undefined;
    type?: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT" | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    judgeName?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    executedBy?: string | undefined;
    executedAt?: Date | undefined;
    executionNotes?: string | undefined;
    attachments?: string[] | undefined;
}>;
export declare const CreateOrderSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    caseId: z.ZodString;
    orderNumber: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["INTERIM_ORDER", "FINAL_ORDER", "EXECUTION_ORDER", "STAY_ORDER", "INJUNCTION", "DECREE", "AWARD", "SETTLEMENT", "OTHER"]>>;
    status: z.ZodDefault<z.ZodEnum<["DRAFT", "PENDING", "APPROVED", "REJECTED", "EXECUTED", "CANCELLED"]>>;
    priority: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    courtName: z.ZodString;
    judgeName: z.ZodOptional<z.ZodString>;
    orderDate: z.ZodOptional<z.ZodDate>;
    effectiveDate: z.ZodOptional<z.ZodDate>;
    expiryDate: z.ZodOptional<z.ZodDate>;
    createdBy: z.ZodString;
    approvedBy: z.ZodOptional<z.ZodString>;
    approvedAt: z.ZodOptional<z.ZodDate>;
    executedBy: z.ZodOptional<z.ZodString>;
    executedAt: z.ZodOptional<z.ZodDate>;
    executionNotes: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isConfidential: z.ZodDefault<z.ZodBoolean>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "id" | "createdAt" | "updatedAt" | "approvedAt" | "executedAt">, "strip", z.ZodTypeAny, {
    status: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED";
    type: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT";
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    caseId: string;
    courtName: string;
    tags: string[];
    isConfidential: boolean;
    orderNumber: string;
    content: string;
    createdBy: string;
    attachments: string[];
    description?: string | undefined;
    judgeName?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    approvedBy?: string | undefined;
    executedBy?: string | undefined;
    executionNotes?: string | undefined;
}, {
    title: string;
    caseId: string;
    courtName: string;
    orderNumber: string;
    content: string;
    createdBy: string;
    status?: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED" | undefined;
    type?: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT" | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    judgeName?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    approvedBy?: string | undefined;
    executedBy?: string | undefined;
    executionNotes?: string | undefined;
    attachments?: string[] | undefined;
}>;
export declare const UpdateOrderSchema: z.ZodObject<{
    status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["DRAFT", "PENDING", "APPROVED", "REJECTED", "EXECUTED", "CANCELLED"]>>>;
    type: z.ZodOptional<z.ZodDefault<z.ZodEnum<["INTERIM_ORDER", "FINAL_ORDER", "EXECUTION_ORDER", "STAY_ORDER", "INJUNCTION", "DECREE", "AWARD", "SETTLEMENT", "OTHER"]>>>;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    priority: z.ZodOptional<z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>>;
    caseId: z.ZodOptional<z.ZodString>;
    courtName: z.ZodOptional<z.ZodString>;
    tags: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    isConfidential: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    judgeName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    orderNumber: z.ZodOptional<z.ZodString>;
    content: z.ZodOptional<z.ZodString>;
    orderDate: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    effectiveDate: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    expiryDate: z.ZodOptional<z.ZodOptional<z.ZodDate>>;
    createdBy: z.ZodOptional<z.ZodString>;
    approvedBy: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    executedBy: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    executionNotes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    attachments: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
}, "strip", z.ZodTypeAny, {
    status?: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED" | undefined;
    type?: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT" | undefined;
    title?: string | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    caseId?: string | undefined;
    courtName?: string | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    judgeName?: string | undefined;
    orderNumber?: string | undefined;
    content?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    createdBy?: string | undefined;
    approvedBy?: string | undefined;
    executedBy?: string | undefined;
    executionNotes?: string | undefined;
    attachments?: string[] | undefined;
}, {
    status?: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED" | undefined;
    type?: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT" | undefined;
    title?: string | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    caseId?: string | undefined;
    courtName?: string | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    judgeName?: string | undefined;
    orderNumber?: string | undefined;
    content?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    createdBy?: string | undefined;
    approvedBy?: string | undefined;
    executedBy?: string | undefined;
    executionNotes?: string | undefined;
    attachments?: string[] | undefined;
}>;
export declare const OrderSearchSchema: z.ZodObject<{
    query: z.ZodOptional<z.ZodString>;
    caseId: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<["INTERIM_ORDER", "FINAL_ORDER", "EXECUTION_ORDER", "STAY_ORDER", "INJUNCTION", "DECREE", "AWARD", "SETTLEMENT", "OTHER"]>>;
    status: z.ZodOptional<z.ZodEnum<["DRAFT", "PENDING", "APPROVED", "REJECTED", "EXECUTED", "CANCELLED"]>>;
    priority: z.ZodOptional<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    courtName: z.ZodOptional<z.ZodString>;
    judgeName: z.ZodOptional<z.ZodString>;
    createdBy: z.ZodOptional<z.ZodString>;
    orderDateFrom: z.ZodOptional<z.ZodDate>;
    orderDateTo: z.ZodOptional<z.ZodDate>;
    effectiveDateFrom: z.ZodOptional<z.ZodDate>;
    effectiveDateTo: z.ZodOptional<z.ZodDate>;
    isConfidential: z.ZodOptional<z.ZodBoolean>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    limit: z.ZodDefault<z.ZodNumber>;
    offset: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    offset: number;
    query?: string | undefined;
    status?: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED" | undefined;
    type?: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT" | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    caseId?: string | undefined;
    courtName?: string | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    judgeName?: string | undefined;
    createdBy?: string | undefined;
    orderDateFrom?: Date | undefined;
    orderDateTo?: Date | undefined;
    effectiveDateFrom?: Date | undefined;
    effectiveDateTo?: Date | undefined;
}, {
    query?: string | undefined;
    status?: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED" | undefined;
    type?: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT" | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    caseId?: string | undefined;
    courtName?: string | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    judgeName?: string | undefined;
    createdBy?: string | undefined;
    orderDateFrom?: Date | undefined;
    orderDateTo?: Date | undefined;
    effectiveDateFrom?: Date | undefined;
    effectiveDateTo?: Date | undefined;
}>;
export declare const OrderListSchema: z.ZodObject<{
    id: z.ZodString;
    caseId: z.ZodString;
    orderNumber: z.ZodString;
    type: z.ZodEnum<["INTERIM_ORDER", "FINAL_ORDER", "EXECUTION_ORDER", "STAY_ORDER", "INJUNCTION", "DECREE", "AWARD", "SETTLEMENT", "OTHER"]>;
    status: z.ZodEnum<["DRAFT", "PENDING", "APPROVED", "REJECTED", "EXECUTED", "CANCELLED"]>;
    priority: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>;
    title: z.ZodString;
    courtName: z.ZodString;
    orderDate: z.ZodOptional<z.ZodDate>;
    effectiveDate: z.ZodOptional<z.ZodDate>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED";
    type: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT";
    createdAt: Date;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    caseId: string;
    courtName: string;
    orderNumber: string;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
}, {
    id: string;
    status: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED";
    type: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT";
    createdAt: Date;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    caseId: string;
    courtName: string;
    orderNumber: string;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
}>;
export declare const OrderWithCaseSchema: z.ZodObject<{
    id: z.ZodString;
    caseId: z.ZodString;
    orderNumber: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["INTERIM_ORDER", "FINAL_ORDER", "EXECUTION_ORDER", "STAY_ORDER", "INJUNCTION", "DECREE", "AWARD", "SETTLEMENT", "OTHER"]>>;
    status: z.ZodDefault<z.ZodEnum<["DRAFT", "PENDING", "APPROVED", "REJECTED", "EXECUTED", "CANCELLED"]>>;
    priority: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    courtName: z.ZodString;
    judgeName: z.ZodOptional<z.ZodString>;
    orderDate: z.ZodOptional<z.ZodDate>;
    effectiveDate: z.ZodOptional<z.ZodDate>;
    expiryDate: z.ZodOptional<z.ZodDate>;
    createdBy: z.ZodString;
    approvedBy: z.ZodOptional<z.ZodString>;
    approvedAt: z.ZodOptional<z.ZodDate>;
    executedBy: z.ZodOptional<z.ZodString>;
    executedAt: z.ZodOptional<z.ZodDate>;
    executionNotes: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isConfidential: z.ZodDefault<z.ZodBoolean>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
} & {
    case: z.ZodObject<{
        id: z.ZodString;
        caseNumber: z.ZodString;
        title: z.ZodString;
        status: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        status: string;
        caseNumber: string;
        title: string;
    }, {
        id: string;
        status: string;
        caseNumber: string;
        title: string;
    }>;
}, "strip", z.ZodTypeAny, {
    case: {
        id: string;
        status: string;
        caseNumber: string;
        title: string;
    };
    id: string;
    status: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED";
    type: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT";
    createdAt: Date;
    updatedAt: Date;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    caseId: string;
    courtName: string;
    tags: string[];
    isConfidential: boolean;
    orderNumber: string;
    content: string;
    createdBy: string;
    attachments: string[];
    description?: string | undefined;
    judgeName?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    executedBy?: string | undefined;
    executedAt?: Date | undefined;
    executionNotes?: string | undefined;
}, {
    case: {
        id: string;
        status: string;
        caseNumber: string;
        title: string;
    };
    id: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    caseId: string;
    courtName: string;
    orderNumber: string;
    content: string;
    createdBy: string;
    status?: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED" | undefined;
    type?: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT" | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    judgeName?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    executedBy?: string | undefined;
    executedAt?: Date | undefined;
    executionNotes?: string | undefined;
    attachments?: string[] | undefined;
}>;
export declare const OrderWithCreatorSchema: z.ZodObject<{
    id: z.ZodString;
    caseId: z.ZodString;
    orderNumber: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["INTERIM_ORDER", "FINAL_ORDER", "EXECUTION_ORDER", "STAY_ORDER", "INJUNCTION", "DECREE", "AWARD", "SETTLEMENT", "OTHER"]>>;
    status: z.ZodDefault<z.ZodEnum<["DRAFT", "PENDING", "APPROVED", "REJECTED", "EXECUTED", "CANCELLED"]>>;
    priority: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "URGENT"]>>;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    courtName: z.ZodString;
    judgeName: z.ZodOptional<z.ZodString>;
    orderDate: z.ZodOptional<z.ZodDate>;
    effectiveDate: z.ZodOptional<z.ZodDate>;
    expiryDate: z.ZodOptional<z.ZodDate>;
    createdBy: z.ZodString;
    approvedBy: z.ZodOptional<z.ZodString>;
    approvedAt: z.ZodOptional<z.ZodDate>;
    executedBy: z.ZodOptional<z.ZodString>;
    executedAt: z.ZodOptional<z.ZodDate>;
    executionNotes: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    isConfidential: z.ZodDefault<z.ZodBoolean>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
} & {
    creator: z.ZodObject<{
        id: z.ZodString;
        firstName: z.ZodString;
        lastName: z.ZodString;
        email: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    }>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED";
    type: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT";
    createdAt: Date;
    updatedAt: Date;
    title: string;
    priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
    caseId: string;
    courtName: string;
    tags: string[];
    isConfidential: boolean;
    orderNumber: string;
    content: string;
    createdBy: string;
    attachments: string[];
    creator: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    };
    description?: string | undefined;
    judgeName?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    executedBy?: string | undefined;
    executedAt?: Date | undefined;
    executionNotes?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    caseId: string;
    courtName: string;
    orderNumber: string;
    content: string;
    createdBy: string;
    creator: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
    };
    status?: "PENDING" | "CANCELLED" | "DRAFT" | "APPROVED" | "REJECTED" | "EXECUTED" | undefined;
    type?: "OTHER" | "INTERIM_ORDER" | "FINAL_ORDER" | "EXECUTION_ORDER" | "STAY_ORDER" | "INJUNCTION" | "DECREE" | "AWARD" | "SETTLEMENT" | undefined;
    description?: string | undefined;
    priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT" | undefined;
    tags?: string[] | undefined;
    isConfidential?: boolean | undefined;
    judgeName?: string | undefined;
    orderDate?: Date | undefined;
    effectiveDate?: Date | undefined;
    expiryDate?: Date | undefined;
    approvedBy?: string | undefined;
    approvedAt?: Date | undefined;
    executedBy?: string | undefined;
    executedAt?: Date | undefined;
    executionNotes?: string | undefined;
    attachments?: string[] | undefined;
}>;
export declare const OrderApprovalSchema: z.ZodObject<{
    orderId: z.ZodString;
    status: z.ZodEnum<["APPROVED", "REJECTED"]>;
    comments: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "APPROVED" | "REJECTED";
    orderId: string;
    comments?: string | undefined;
}, {
    status: "APPROVED" | "REJECTED";
    orderId: string;
    comments?: string | undefined;
}>;
export declare const OrderExecutionSchema: z.ZodObject<{
    orderId: z.ZodString;
    executionNotes: z.ZodOptional<z.ZodString>;
    executedBy: z.ZodString;
}, "strip", z.ZodTypeAny, {
    executedBy: string;
    orderId: string;
    executionNotes?: string | undefined;
}, {
    executedBy: string;
    orderId: string;
    executionNotes?: string | undefined;
}>;
export declare const OrderStatisticsSchema: z.ZodObject<{
    total: z.ZodNumber;
    draft: z.ZodNumber;
    pending: z.ZodNumber;
    approved: z.ZodNumber;
    rejected: z.ZodNumber;
    executed: z.ZodNumber;
    cancelled: z.ZodNumber;
    byType: z.ZodRecord<z.ZodString, z.ZodNumber>;
    byPriority: z.ZodObject<{
        low: z.ZodNumber;
        medium: z.ZodNumber;
        high: z.ZodNumber;
        urgent: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        low: number;
        medium: number;
        high: number;
        urgent: number;
    }, {
        low: number;
        medium: number;
        high: number;
        urgent: number;
    }>;
}, "strip", z.ZodTypeAny, {
    total: number;
    byPriority: {
        low: number;
        medium: number;
        high: number;
        urgent: number;
    };
    byType: Record<string, number>;
    cancelled: number;
    draft: number;
    pending: number;
    approved: number;
    rejected: number;
    executed: number;
}, {
    total: number;
    byPriority: {
        low: number;
        medium: number;
        high: number;
        urgent: number;
    };
    byType: Record<string, number>;
    cancelled: number;
    draft: number;
    pending: number;
    approved: number;
    rejected: number;
    executed: number;
}>;
export type Order = z.infer<typeof OrderSchema>;
export type CreateOrder = z.infer<typeof CreateOrderSchema>;
export type UpdateOrder = z.infer<typeof UpdateOrderSchema>;
export type OrderSearch = z.infer<typeof OrderSearchSchema>;
export type OrderList = z.infer<typeof OrderListSchema>;
export type OrderWithCase = z.infer<typeof OrderWithCaseSchema>;
export type OrderWithCreator = z.infer<typeof OrderWithCreatorSchema>;
export type OrderApproval = z.infer<typeof OrderApprovalSchema>;
export type OrderExecution = z.infer<typeof OrderExecutionSchema>;
export type OrderStatistics = z.infer<typeof OrderStatisticsSchema>;
//# sourceMappingURL=order.d.ts.map