import { z } from 'zod';
export declare const PartyTypeSchema: z.ZodEnum<["INDIVIDUAL", "COMPANY", "GOVERNMENT", "NGO", "OTHER"]>;
export type PartyType = z.infer<typeof PartyTypeSchema>;
export declare const PartyRoleSchema: z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>;
export type PartyRole = z.infer<typeof PartyRoleSchema>;
export declare const PartySchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["INDIVIDUAL", "COMPANY", "GOVERNMENT", "NGO", "OTHER"]>>;
    role: z.ZodDefault<z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>>;
    caseId: z.ZodString;
    contactPerson: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    country: z.ZodDefault<z.ZodString>;
    pincode: z.ZodOptional<z.ZodString>;
    registrationNumber: z.ZodOptional<z.ZodString>;
    panNumber: z.ZodOptional<z.ZodString>;
    gstNumber: z.ZodOptional<z.ZodString>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    notes: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    role: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT";
    type: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO";
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    caseId: string;
    name: string;
    country: string;
    email?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    caseId: string;
    name: string;
    email?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    type?: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO" | undefined;
    isActive?: boolean | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
}>;
export declare const CreatePartySchema: z.ZodObject<Omit<{
    id: z.ZodString;
    name: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["INDIVIDUAL", "COMPANY", "GOVERNMENT", "NGO", "OTHER"]>>;
    role: z.ZodDefault<z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>>;
    caseId: z.ZodString;
    contactPerson: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    country: z.ZodDefault<z.ZodString>;
    pincode: z.ZodOptional<z.ZodString>;
    registrationNumber: z.ZodOptional<z.ZodString>;
    panNumber: z.ZodOptional<z.ZodString>;
    gstNumber: z.ZodOptional<z.ZodString>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    notes: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "id" | "createdAt" | "updatedAt">, "strip", z.ZodTypeAny, {
    role: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT";
    type: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO";
    isActive: boolean;
    caseId: string;
    name: string;
    country: string;
    email?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
}, {
    caseId: string;
    name: string;
    email?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    type?: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO" | undefined;
    isActive?: boolean | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
}>;
export declare const UpdatePartySchema: z.ZodObject<{
    email: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    role: z.ZodOptional<z.ZodDefault<z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>>>;
    type: z.ZodOptional<z.ZodDefault<z.ZodEnum<["INDIVIDUAL", "COMPANY", "GOVERNMENT", "NGO", "OTHER"]>>>;
    isActive: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    caseId: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    address: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    name: z.ZodOptional<z.ZodString>;
    contactPerson: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    city: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    state: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    country: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    pincode: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    registrationNumber: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    panNumber: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    gstNumber: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    email?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    type?: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO" | undefined;
    isActive?: boolean | undefined;
    caseId?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    name?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
}, {
    email?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    type?: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO" | undefined;
    isActive?: boolean | undefined;
    caseId?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    name?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
}>;
export declare const PartySearchSchema: z.ZodObject<{
    query: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<["INDIVIDUAL", "COMPANY", "GOVERNMENT", "NGO", "OTHER"]>>;
    role: z.ZodOptional<z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>>;
    caseId: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    isActive: z.ZodOptional<z.ZodBoolean>;
    limit: z.ZodDefault<z.ZodNumber>;
    offset: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    offset: number;
    query?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    type?: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO" | undefined;
    isActive?: boolean | undefined;
    caseId?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
}, {
    query?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    type?: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO" | undefined;
    isActive?: boolean | undefined;
    caseId?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    city?: string | undefined;
    state?: string | undefined;
}>;
export declare const PartyListSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    type: z.ZodEnum<["INDIVIDUAL", "COMPANY", "GOVERNMENT", "NGO", "OTHER"]>;
    role: z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>;
    caseId: z.ZodString;
    contactPerson: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    isActive: z.ZodBoolean;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    role: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT";
    type: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO";
    isActive: boolean;
    createdAt: Date;
    caseId: string;
    name: string;
    email?: string | undefined;
    phone?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
}, {
    id: string;
    role: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT";
    type: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO";
    isActive: boolean;
    createdAt: Date;
    caseId: string;
    name: string;
    email?: string | undefined;
    phone?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
}>;
export declare const PartyWithCaseSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["INDIVIDUAL", "COMPANY", "GOVERNMENT", "NGO", "OTHER"]>>;
    role: z.ZodDefault<z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>>;
    caseId: z.ZodString;
    contactPerson: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    country: z.ZodDefault<z.ZodString>;
    pincode: z.ZodOptional<z.ZodString>;
    registrationNumber: z.ZodOptional<z.ZodString>;
    panNumber: z.ZodOptional<z.ZodString>;
    gstNumber: z.ZodOptional<z.ZodString>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    notes: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
} & {
    case: z.ZodObject<{
        id: z.ZodString;
        caseNumber: z.ZodString;
        title: z.ZodString;
        status: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        status: string;
        caseNumber: string;
        title: string;
    }, {
        id: string;
        status: string;
        caseNumber: string;
        title: string;
    }>;
}, "strip", z.ZodTypeAny, {
    case: {
        id: string;
        status: string;
        caseNumber: string;
        title: string;
    };
    id: string;
    role: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT";
    type: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO";
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    caseId: string;
    name: string;
    country: string;
    email?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
}, {
    case: {
        id: string;
        status: string;
        caseNumber: string;
        title: string;
    };
    id: string;
    createdAt: Date;
    updatedAt: Date;
    caseId: string;
    name: string;
    email?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    type?: "OTHER" | "INDIVIDUAL" | "COMPANY" | "GOVERNMENT" | "NGO" | undefined;
    isActive?: boolean | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
}>;
export declare const IndividualPartySchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    role: z.ZodDefault<z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>>;
    caseId: z.ZodString;
    contactPerson: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    country: z.ZodDefault<z.ZodString>;
    pincode: z.ZodOptional<z.ZodString>;
    registrationNumber: z.ZodOptional<z.ZodString>;
    panNumber: z.ZodOptional<z.ZodString>;
    gstNumber: z.ZodOptional<z.ZodString>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    notes: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
} & {
    type: z.ZodLiteral<"INDIVIDUAL">;
    firstName: z.ZodString;
    lastName: z.ZodString;
    middleName: z.ZodOptional<z.ZodString>;
    dateOfBirth: z.ZodOptional<z.ZodDate>;
    gender: z.ZodOptional<z.ZodEnum<["MALE", "FEMALE", "OTHER"]>>;
    occupation: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    firstName: string;
    lastName: string;
    role: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT";
    type: "INDIVIDUAL";
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    caseId: string;
    name: string;
    country: string;
    email?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    dateOfBirth?: Date | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
    middleName?: string | undefined;
    gender?: "OTHER" | "MALE" | "FEMALE" | undefined;
    occupation?: string | undefined;
}, {
    id: string;
    firstName: string;
    lastName: string;
    type: "INDIVIDUAL";
    createdAt: Date;
    updatedAt: Date;
    caseId: string;
    name: string;
    email?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    isActive?: boolean | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    dateOfBirth?: Date | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
    middleName?: string | undefined;
    gender?: "OTHER" | "MALE" | "FEMALE" | undefined;
    occupation?: string | undefined;
}>;
export declare const CompanyPartySchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    role: z.ZodDefault<z.ZodEnum<["PLAINTIFF", "DEFENDANT", "THIRD_PARTY", "WITNESS", "EXPERT", "OTHER"]>>;
    caseId: z.ZodString;
    contactPerson: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    country: z.ZodDefault<z.ZodString>;
    pincode: z.ZodOptional<z.ZodString>;
    registrationNumber: z.ZodOptional<z.ZodString>;
    panNumber: z.ZodOptional<z.ZodString>;
    gstNumber: z.ZodOptional<z.ZodString>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    notes: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
} & {
    type: z.ZodLiteral<"COMPANY">;
    companyName: z.ZodString;
    incorporationDate: z.ZodOptional<z.ZodDate>;
    businessType: z.ZodOptional<z.ZodString>;
    authorizedSignatory: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    role: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT";
    type: "COMPANY";
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    caseId: string;
    name: string;
    country: string;
    companyName: string;
    email?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
    incorporationDate?: Date | undefined;
    businessType?: string | undefined;
    authorizedSignatory?: string | undefined;
}, {
    id: string;
    type: "COMPANY";
    createdAt: Date;
    updatedAt: Date;
    caseId: string;
    name: string;
    companyName: string;
    email?: string | undefined;
    role?: "OTHER" | "PLAINTIFF" | "DEFENDANT" | "THIRD_PARTY" | "WITNESS" | "EXPERT" | undefined;
    isActive?: boolean | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    contactPerson?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    pincode?: string | undefined;
    registrationNumber?: string | undefined;
    panNumber?: string | undefined;
    gstNumber?: string | undefined;
    notes?: string | undefined;
    incorporationDate?: Date | undefined;
    businessType?: string | undefined;
    authorizedSignatory?: string | undefined;
}>;
export type Party = z.infer<typeof PartySchema>;
export type CreateParty = z.infer<typeof CreatePartySchema>;
export type UpdateParty = z.infer<typeof UpdatePartySchema>;
export type PartySearch = z.infer<typeof PartySearchSchema>;
export type PartyList = z.infer<typeof PartyListSchema>;
export type PartyWithCase = z.infer<typeof PartyWithCaseSchema>;
export type IndividualParty = z.infer<typeof IndividualPartySchema>;
export type CompanyParty = z.infer<typeof CompanyPartySchema>;
//# sourceMappingURL=party.d.ts.map