import { z } from 'zod';
export declare const UserPendingSummarySchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    date: z.ZodDate;
    pendingCases: z.ZodDefault<z.ZodNumber>;
    urgentCases: z.ZodDefault<z.ZodNumber>;
    overdueCases: z.ZodDefault<z.ZodNumber>;
    pendingTasks: z.ZodDefault<z.ZodNumber>;
    urgentTasks: z.ZodDefault<z.ZodNumber>;
    overdueTasks: z.ZodDefault<z.ZodNumber>;
    personalTasks: z.ZodDefault<z.ZodNumber>;
    adminTasks: z.ZodDefault<z.ZodNumber>;
    bizDevTasks: z.ZodDefault<z.ZodNumber>;
    pendingSubtasks: z.ZodDefault<z.ZodNumber>;
    urgentSubtasks: z.ZodDefault<z.ZodNumber>;
    overdueSubtasks: z.ZodDefault<z.ZodNumber>;
    upcomingHearings: z.ZodDefault<z.ZodNumber>;
    hearingsThisWeek: z.ZodDefault<z.ZodNumber>;
    hearingsToday: z.ZodDefault<z.ZodNumber>;
    pendingOrders: z.ZodDefault<z.ZodNumber>;
    ordersToExecute: z.ZodDefault<z.ZodNumber>;
    overdueOrders: z.ZodDefault<z.ZodNumber>;
    pendingWorklogs: z.ZodDefault<z.ZodNumber>;
    worklogsToApprove: z.ZodDefault<z.ZodNumber>;
    pendingLeaveRequests: z.ZodDefault<z.ZodNumber>;
    leaveRequestsToApprove: z.ZodDefault<z.ZodNumber>;
    pendingDocuments: z.ZodDefault<z.ZodNumber>;
    documentsToReview: z.ZodDefault<z.ZodNumber>;
    teamInvitations: z.ZodDefault<z.ZodNumber>;
    pendingTeamTasks: z.ZodDefault<z.ZodNumber>;
    totalPendingItems: z.ZodDefault<z.ZodNumber>;
    totalUrgentItems: z.ZodDefault<z.ZodNumber>;
    totalOverdueItems: z.ZodDefault<z.ZodNumber>;
    highPriorityItems: z.ZodDefault<z.ZodNumber>;
    mediumPriorityItems: z.ZodDefault<z.ZodNumber>;
    lowPriorityItems: z.ZodDefault<z.ZodNumber>;
    itemsDueToday: z.ZodDefault<z.ZodNumber>;
    itemsDueThisWeek: z.ZodDefault<z.ZodNumber>;
    itemsDueThisMonth: z.ZodDefault<z.ZodNumber>;
    workloadLevel: z.ZodDefault<z.ZodEnum<["LOW", "MODERATE", "HIGH", "CRITICAL"]>>;
    estimatedHoursToComplete: z.ZodOptional<z.ZodNumber>;
    lastUpdated: z.ZodDate;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    date: Date;
    createdAt: Date;
    userId: string;
    pendingCases: number;
    urgentCases: number;
    overdueCases: number;
    pendingTasks: number;
    urgentTasks: number;
    overdueTasks: number;
    personalTasks: number;
    adminTasks: number;
    bizDevTasks: number;
    pendingSubtasks: number;
    urgentSubtasks: number;
    overdueSubtasks: number;
    upcomingHearings: number;
    hearingsThisWeek: number;
    hearingsToday: number;
    pendingOrders: number;
    ordersToExecute: number;
    overdueOrders: number;
    pendingWorklogs: number;
    worklogsToApprove: number;
    pendingLeaveRequests: number;
    leaveRequestsToApprove: number;
    pendingDocuments: number;
    documentsToReview: number;
    teamInvitations: number;
    pendingTeamTasks: number;
    totalPendingItems: number;
    totalUrgentItems: number;
    totalOverdueItems: number;
    highPriorityItems: number;
    mediumPriorityItems: number;
    lowPriorityItems: number;
    itemsDueToday: number;
    itemsDueThisWeek: number;
    itemsDueThisMonth: number;
    workloadLevel: "LOW" | "HIGH" | "CRITICAL" | "MODERATE";
    lastUpdated: Date;
    estimatedHoursToComplete?: number | undefined;
}, {
    id: string;
    date: Date;
    createdAt: Date;
    userId: string;
    lastUpdated: Date;
    pendingCases?: number | undefined;
    urgentCases?: number | undefined;
    overdueCases?: number | undefined;
    pendingTasks?: number | undefined;
    urgentTasks?: number | undefined;
    overdueTasks?: number | undefined;
    personalTasks?: number | undefined;
    adminTasks?: number | undefined;
    bizDevTasks?: number | undefined;
    pendingSubtasks?: number | undefined;
    urgentSubtasks?: number | undefined;
    overdueSubtasks?: number | undefined;
    upcomingHearings?: number | undefined;
    hearingsThisWeek?: number | undefined;
    hearingsToday?: number | undefined;
    pendingOrders?: number | undefined;
    ordersToExecute?: number | undefined;
    overdueOrders?: number | undefined;
    pendingWorklogs?: number | undefined;
    worklogsToApprove?: number | undefined;
    pendingLeaveRequests?: number | undefined;
    leaveRequestsToApprove?: number | undefined;
    pendingDocuments?: number | undefined;
    documentsToReview?: number | undefined;
    teamInvitations?: number | undefined;
    pendingTeamTasks?: number | undefined;
    totalPendingItems?: number | undefined;
    totalUrgentItems?: number | undefined;
    totalOverdueItems?: number | undefined;
    highPriorityItems?: number | undefined;
    mediumPriorityItems?: number | undefined;
    lowPriorityItems?: number | undefined;
    itemsDueToday?: number | undefined;
    itemsDueThisWeek?: number | undefined;
    itemsDueThisMonth?: number | undefined;
    workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
    estimatedHoursToComplete?: number | undefined;
}>;
export declare const CreateUserPendingSummarySchema: z.ZodObject<Omit<{
    id: z.ZodString;
    userId: z.ZodString;
    date: z.ZodDate;
    pendingCases: z.ZodDefault<z.ZodNumber>;
    urgentCases: z.ZodDefault<z.ZodNumber>;
    overdueCases: z.ZodDefault<z.ZodNumber>;
    pendingTasks: z.ZodDefault<z.ZodNumber>;
    urgentTasks: z.ZodDefault<z.ZodNumber>;
    overdueTasks: z.ZodDefault<z.ZodNumber>;
    personalTasks: z.ZodDefault<z.ZodNumber>;
    adminTasks: z.ZodDefault<z.ZodNumber>;
    bizDevTasks: z.ZodDefault<z.ZodNumber>;
    pendingSubtasks: z.ZodDefault<z.ZodNumber>;
    urgentSubtasks: z.ZodDefault<z.ZodNumber>;
    overdueSubtasks: z.ZodDefault<z.ZodNumber>;
    upcomingHearings: z.ZodDefault<z.ZodNumber>;
    hearingsThisWeek: z.ZodDefault<z.ZodNumber>;
    hearingsToday: z.ZodDefault<z.ZodNumber>;
    pendingOrders: z.ZodDefault<z.ZodNumber>;
    ordersToExecute: z.ZodDefault<z.ZodNumber>;
    overdueOrders: z.ZodDefault<z.ZodNumber>;
    pendingWorklogs: z.ZodDefault<z.ZodNumber>;
    worklogsToApprove: z.ZodDefault<z.ZodNumber>;
    pendingLeaveRequests: z.ZodDefault<z.ZodNumber>;
    leaveRequestsToApprove: z.ZodDefault<z.ZodNumber>;
    pendingDocuments: z.ZodDefault<z.ZodNumber>;
    documentsToReview: z.ZodDefault<z.ZodNumber>;
    teamInvitations: z.ZodDefault<z.ZodNumber>;
    pendingTeamTasks: z.ZodDefault<z.ZodNumber>;
    totalPendingItems: z.ZodDefault<z.ZodNumber>;
    totalUrgentItems: z.ZodDefault<z.ZodNumber>;
    totalOverdueItems: z.ZodDefault<z.ZodNumber>;
    highPriorityItems: z.ZodDefault<z.ZodNumber>;
    mediumPriorityItems: z.ZodDefault<z.ZodNumber>;
    lowPriorityItems: z.ZodDefault<z.ZodNumber>;
    itemsDueToday: z.ZodDefault<z.ZodNumber>;
    itemsDueThisWeek: z.ZodDefault<z.ZodNumber>;
    itemsDueThisMonth: z.ZodDefault<z.ZodNumber>;
    workloadLevel: z.ZodDefault<z.ZodEnum<["LOW", "MODERATE", "HIGH", "CRITICAL"]>>;
    estimatedHoursToComplete: z.ZodOptional<z.ZodNumber>;
    lastUpdated: z.ZodDate;
    createdAt: z.ZodDate;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    date: Date;
    userId: string;
    pendingCases: number;
    urgentCases: number;
    overdueCases: number;
    pendingTasks: number;
    urgentTasks: number;
    overdueTasks: number;
    personalTasks: number;
    adminTasks: number;
    bizDevTasks: number;
    pendingSubtasks: number;
    urgentSubtasks: number;
    overdueSubtasks: number;
    upcomingHearings: number;
    hearingsThisWeek: number;
    hearingsToday: number;
    pendingOrders: number;
    ordersToExecute: number;
    overdueOrders: number;
    pendingWorklogs: number;
    worklogsToApprove: number;
    pendingLeaveRequests: number;
    leaveRequestsToApprove: number;
    pendingDocuments: number;
    documentsToReview: number;
    teamInvitations: number;
    pendingTeamTasks: number;
    totalPendingItems: number;
    totalUrgentItems: number;
    totalOverdueItems: number;
    highPriorityItems: number;
    mediumPriorityItems: number;
    lowPriorityItems: number;
    itemsDueToday: number;
    itemsDueThisWeek: number;
    itemsDueThisMonth: number;
    workloadLevel: "LOW" | "HIGH" | "CRITICAL" | "MODERATE";
    lastUpdated: Date;
    estimatedHoursToComplete?: number | undefined;
}, {
    date: Date;
    userId: string;
    lastUpdated: Date;
    pendingCases?: number | undefined;
    urgentCases?: number | undefined;
    overdueCases?: number | undefined;
    pendingTasks?: number | undefined;
    urgentTasks?: number | undefined;
    overdueTasks?: number | undefined;
    personalTasks?: number | undefined;
    adminTasks?: number | undefined;
    bizDevTasks?: number | undefined;
    pendingSubtasks?: number | undefined;
    urgentSubtasks?: number | undefined;
    overdueSubtasks?: number | undefined;
    upcomingHearings?: number | undefined;
    hearingsThisWeek?: number | undefined;
    hearingsToday?: number | undefined;
    pendingOrders?: number | undefined;
    ordersToExecute?: number | undefined;
    overdueOrders?: number | undefined;
    pendingWorklogs?: number | undefined;
    worklogsToApprove?: number | undefined;
    pendingLeaveRequests?: number | undefined;
    leaveRequestsToApprove?: number | undefined;
    pendingDocuments?: number | undefined;
    documentsToReview?: number | undefined;
    teamInvitations?: number | undefined;
    pendingTeamTasks?: number | undefined;
    totalPendingItems?: number | undefined;
    totalUrgentItems?: number | undefined;
    totalOverdueItems?: number | undefined;
    highPriorityItems?: number | undefined;
    mediumPriorityItems?: number | undefined;
    lowPriorityItems?: number | undefined;
    itemsDueToday?: number | undefined;
    itemsDueThisWeek?: number | undefined;
    itemsDueThisMonth?: number | undefined;
    workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
    estimatedHoursToComplete?: number | undefined;
}>;
export declare const UpdateUserPendingSummarySchema: z.ZodObject<{
    date: z.ZodOptional<z.ZodDate>;
    userId: z.ZodOptional<z.ZodString>;
    pendingCases: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    urgentCases: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    overdueCases: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    pendingTasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    urgentTasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    overdueTasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    personalTasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    adminTasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    bizDevTasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    pendingSubtasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    urgentSubtasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    overdueSubtasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    upcomingHearings: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    hearingsThisWeek: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    hearingsToday: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    pendingOrders: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    ordersToExecute: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    overdueOrders: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    pendingWorklogs: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    worklogsToApprove: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    pendingLeaveRequests: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    leaveRequestsToApprove: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    pendingDocuments: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    documentsToReview: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    teamInvitations: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    pendingTeamTasks: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    totalPendingItems: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    totalUrgentItems: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    totalOverdueItems: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    highPriorityItems: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    mediumPriorityItems: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    lowPriorityItems: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    itemsDueToday: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    itemsDueThisWeek: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    itemsDueThisMonth: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    workloadLevel: z.ZodOptional<z.ZodDefault<z.ZodEnum<["LOW", "MODERATE", "HIGH", "CRITICAL"]>>>;
    estimatedHoursToComplete: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    lastUpdated: z.ZodOptional<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    date?: Date | undefined;
    userId?: string | undefined;
    pendingCases?: number | undefined;
    urgentCases?: number | undefined;
    overdueCases?: number | undefined;
    pendingTasks?: number | undefined;
    urgentTasks?: number | undefined;
    overdueTasks?: number | undefined;
    personalTasks?: number | undefined;
    adminTasks?: number | undefined;
    bizDevTasks?: number | undefined;
    pendingSubtasks?: number | undefined;
    urgentSubtasks?: number | undefined;
    overdueSubtasks?: number | undefined;
    upcomingHearings?: number | undefined;
    hearingsThisWeek?: number | undefined;
    hearingsToday?: number | undefined;
    pendingOrders?: number | undefined;
    ordersToExecute?: number | undefined;
    overdueOrders?: number | undefined;
    pendingWorklogs?: number | undefined;
    worklogsToApprove?: number | undefined;
    pendingLeaveRequests?: number | undefined;
    leaveRequestsToApprove?: number | undefined;
    pendingDocuments?: number | undefined;
    documentsToReview?: number | undefined;
    teamInvitations?: number | undefined;
    pendingTeamTasks?: number | undefined;
    totalPendingItems?: number | undefined;
    totalUrgentItems?: number | undefined;
    totalOverdueItems?: number | undefined;
    highPriorityItems?: number | undefined;
    mediumPriorityItems?: number | undefined;
    lowPriorityItems?: number | undefined;
    itemsDueToday?: number | undefined;
    itemsDueThisWeek?: number | undefined;
    itemsDueThisMonth?: number | undefined;
    workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
    estimatedHoursToComplete?: number | undefined;
    lastUpdated?: Date | undefined;
}, {
    date?: Date | undefined;
    userId?: string | undefined;
    pendingCases?: number | undefined;
    urgentCases?: number | undefined;
    overdueCases?: number | undefined;
    pendingTasks?: number | undefined;
    urgentTasks?: number | undefined;
    overdueTasks?: number | undefined;
    personalTasks?: number | undefined;
    adminTasks?: number | undefined;
    bizDevTasks?: number | undefined;
    pendingSubtasks?: number | undefined;
    urgentSubtasks?: number | undefined;
    overdueSubtasks?: number | undefined;
    upcomingHearings?: number | undefined;
    hearingsThisWeek?: number | undefined;
    hearingsToday?: number | undefined;
    pendingOrders?: number | undefined;
    ordersToExecute?: number | undefined;
    overdueOrders?: number | undefined;
    pendingWorklogs?: number | undefined;
    worklogsToApprove?: number | undefined;
    pendingLeaveRequests?: number | undefined;
    leaveRequestsToApprove?: number | undefined;
    pendingDocuments?: number | undefined;
    documentsToReview?: number | undefined;
    teamInvitations?: number | undefined;
    pendingTeamTasks?: number | undefined;
    totalPendingItems?: number | undefined;
    totalUrgentItems?: number | undefined;
    totalOverdueItems?: number | undefined;
    highPriorityItems?: number | undefined;
    mediumPriorityItems?: number | undefined;
    lowPriorityItems?: number | undefined;
    itemsDueToday?: number | undefined;
    itemsDueThisWeek?: number | undefined;
    itemsDueThisMonth?: number | undefined;
    workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
    estimatedHoursToComplete?: number | undefined;
    lastUpdated?: Date | undefined;
}>;
export declare const UserPendingSummarySearchSchema: z.ZodObject<{
    userId: z.ZodOptional<z.ZodString>;
    dateFrom: z.ZodOptional<z.ZodDate>;
    dateTo: z.ZodOptional<z.ZodDate>;
    workloadLevel: z.ZodOptional<z.ZodEnum<["LOW", "MODERATE", "HIGH", "CRITICAL"]>>;
    hasOverdueItems: z.ZodOptional<z.ZodBoolean>;
    hasUrgentItems: z.ZodOptional<z.ZodBoolean>;
    limit: z.ZodDefault<z.ZodNumber>;
    offset: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    offset: number;
    userId?: string | undefined;
    dateFrom?: Date | undefined;
    dateTo?: Date | undefined;
    workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
    hasOverdueItems?: boolean | undefined;
    hasUrgentItems?: boolean | undefined;
}, {
    userId?: string | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    dateFrom?: Date | undefined;
    dateTo?: Date | undefined;
    workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
    hasOverdueItems?: boolean | undefined;
    hasUrgentItems?: boolean | undefined;
}>;
export declare const UserPendingSummaryListSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    date: z.ZodDate;
    totalPendingItems: z.ZodNumber;
    totalUrgentItems: z.ZodNumber;
    totalOverdueItems: z.ZodNumber;
    workloadLevel: z.ZodEnum<["LOW", "MODERATE", "HIGH", "CRITICAL"]>;
    lastUpdated: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    date: Date;
    userId: string;
    totalPendingItems: number;
    totalUrgentItems: number;
    totalOverdueItems: number;
    workloadLevel: "LOW" | "HIGH" | "CRITICAL" | "MODERATE";
    lastUpdated: Date;
}, {
    id: string;
    date: Date;
    userId: string;
    totalPendingItems: number;
    totalUrgentItems: number;
    totalOverdueItems: number;
    workloadLevel: "LOW" | "HIGH" | "CRITICAL" | "MODERATE";
    lastUpdated: Date;
}>;
export declare const UserPendingSummaryWithUserSchema: z.ZodObject<{
    id: z.ZodString;
    userId: z.ZodString;
    date: z.ZodDate;
    pendingCases: z.ZodDefault<z.ZodNumber>;
    urgentCases: z.ZodDefault<z.ZodNumber>;
    overdueCases: z.ZodDefault<z.ZodNumber>;
    pendingTasks: z.ZodDefault<z.ZodNumber>;
    urgentTasks: z.ZodDefault<z.ZodNumber>;
    overdueTasks: z.ZodDefault<z.ZodNumber>;
    personalTasks: z.ZodDefault<z.ZodNumber>;
    adminTasks: z.ZodDefault<z.ZodNumber>;
    bizDevTasks: z.ZodDefault<z.ZodNumber>;
    pendingSubtasks: z.ZodDefault<z.ZodNumber>;
    urgentSubtasks: z.ZodDefault<z.ZodNumber>;
    overdueSubtasks: z.ZodDefault<z.ZodNumber>;
    upcomingHearings: z.ZodDefault<z.ZodNumber>;
    hearingsThisWeek: z.ZodDefault<z.ZodNumber>;
    hearingsToday: z.ZodDefault<z.ZodNumber>;
    pendingOrders: z.ZodDefault<z.ZodNumber>;
    ordersToExecute: z.ZodDefault<z.ZodNumber>;
    overdueOrders: z.ZodDefault<z.ZodNumber>;
    pendingWorklogs: z.ZodDefault<z.ZodNumber>;
    worklogsToApprove: z.ZodDefault<z.ZodNumber>;
    pendingLeaveRequests: z.ZodDefault<z.ZodNumber>;
    leaveRequestsToApprove: z.ZodDefault<z.ZodNumber>;
    pendingDocuments: z.ZodDefault<z.ZodNumber>;
    documentsToReview: z.ZodDefault<z.ZodNumber>;
    teamInvitations: z.ZodDefault<z.ZodNumber>;
    pendingTeamTasks: z.ZodDefault<z.ZodNumber>;
    totalPendingItems: z.ZodDefault<z.ZodNumber>;
    totalUrgentItems: z.ZodDefault<z.ZodNumber>;
    totalOverdueItems: z.ZodDefault<z.ZodNumber>;
    highPriorityItems: z.ZodDefault<z.ZodNumber>;
    mediumPriorityItems: z.ZodDefault<z.ZodNumber>;
    lowPriorityItems: z.ZodDefault<z.ZodNumber>;
    itemsDueToday: z.ZodDefault<z.ZodNumber>;
    itemsDueThisWeek: z.ZodDefault<z.ZodNumber>;
    itemsDueThisMonth: z.ZodDefault<z.ZodNumber>;
    workloadLevel: z.ZodDefault<z.ZodEnum<["LOW", "MODERATE", "HIGH", "CRITICAL"]>>;
    estimatedHoursToComplete: z.ZodOptional<z.ZodNumber>;
    lastUpdated: z.ZodDate;
    createdAt: z.ZodDate;
} & {
    user: z.ZodObject<{
        id: z.ZodString;
        firstName: z.ZodString;
        lastName: z.ZodString;
        email: z.ZodString;
        role: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        role: string;
    }, {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        role: string;
    }>;
}, "strip", z.ZodTypeAny, {
    user: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        role: string;
    };
    id: string;
    date: Date;
    createdAt: Date;
    userId: string;
    pendingCases: number;
    urgentCases: number;
    overdueCases: number;
    pendingTasks: number;
    urgentTasks: number;
    overdueTasks: number;
    personalTasks: number;
    adminTasks: number;
    bizDevTasks: number;
    pendingSubtasks: number;
    urgentSubtasks: number;
    overdueSubtasks: number;
    upcomingHearings: number;
    hearingsThisWeek: number;
    hearingsToday: number;
    pendingOrders: number;
    ordersToExecute: number;
    overdueOrders: number;
    pendingWorklogs: number;
    worklogsToApprove: number;
    pendingLeaveRequests: number;
    leaveRequestsToApprove: number;
    pendingDocuments: number;
    documentsToReview: number;
    teamInvitations: number;
    pendingTeamTasks: number;
    totalPendingItems: number;
    totalUrgentItems: number;
    totalOverdueItems: number;
    highPriorityItems: number;
    mediumPriorityItems: number;
    lowPriorityItems: number;
    itemsDueToday: number;
    itemsDueThisWeek: number;
    itemsDueThisMonth: number;
    workloadLevel: "LOW" | "HIGH" | "CRITICAL" | "MODERATE";
    lastUpdated: Date;
    estimatedHoursToComplete?: number | undefined;
}, {
    user: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        role: string;
    };
    id: string;
    date: Date;
    createdAt: Date;
    userId: string;
    lastUpdated: Date;
    pendingCases?: number | undefined;
    urgentCases?: number | undefined;
    overdueCases?: number | undefined;
    pendingTasks?: number | undefined;
    urgentTasks?: number | undefined;
    overdueTasks?: number | undefined;
    personalTasks?: number | undefined;
    adminTasks?: number | undefined;
    bizDevTasks?: number | undefined;
    pendingSubtasks?: number | undefined;
    urgentSubtasks?: number | undefined;
    overdueSubtasks?: number | undefined;
    upcomingHearings?: number | undefined;
    hearingsThisWeek?: number | undefined;
    hearingsToday?: number | undefined;
    pendingOrders?: number | undefined;
    ordersToExecute?: number | undefined;
    overdueOrders?: number | undefined;
    pendingWorklogs?: number | undefined;
    worklogsToApprove?: number | undefined;
    pendingLeaveRequests?: number | undefined;
    leaveRequestsToApprove?: number | undefined;
    pendingDocuments?: number | undefined;
    documentsToReview?: number | undefined;
    teamInvitations?: number | undefined;
    pendingTeamTasks?: number | undefined;
    totalPendingItems?: number | undefined;
    totalUrgentItems?: number | undefined;
    totalOverdueItems?: number | undefined;
    highPriorityItems?: number | undefined;
    mediumPriorityItems?: number | undefined;
    lowPriorityItems?: number | undefined;
    itemsDueToday?: number | undefined;
    itemsDueThisWeek?: number | undefined;
    itemsDueThisMonth?: number | undefined;
    workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
    estimatedHoursToComplete?: number | undefined;
}>;
export declare const UserPendingSummaryDashboardSchema: z.ZodObject<{
    userId: z.ZodString;
    userName: z.ZodString;
    userRole: z.ZodString;
    summary: z.ZodObject<{
        id: z.ZodString;
        userId: z.ZodString;
        date: z.ZodDate;
        pendingCases: z.ZodDefault<z.ZodNumber>;
        urgentCases: z.ZodDefault<z.ZodNumber>;
        overdueCases: z.ZodDefault<z.ZodNumber>;
        pendingTasks: z.ZodDefault<z.ZodNumber>;
        urgentTasks: z.ZodDefault<z.ZodNumber>;
        overdueTasks: z.ZodDefault<z.ZodNumber>;
        personalTasks: z.ZodDefault<z.ZodNumber>;
        adminTasks: z.ZodDefault<z.ZodNumber>;
        bizDevTasks: z.ZodDefault<z.ZodNumber>;
        pendingSubtasks: z.ZodDefault<z.ZodNumber>;
        urgentSubtasks: z.ZodDefault<z.ZodNumber>;
        overdueSubtasks: z.ZodDefault<z.ZodNumber>;
        upcomingHearings: z.ZodDefault<z.ZodNumber>;
        hearingsThisWeek: z.ZodDefault<z.ZodNumber>;
        hearingsToday: z.ZodDefault<z.ZodNumber>;
        pendingOrders: z.ZodDefault<z.ZodNumber>;
        ordersToExecute: z.ZodDefault<z.ZodNumber>;
        overdueOrders: z.ZodDefault<z.ZodNumber>;
        pendingWorklogs: z.ZodDefault<z.ZodNumber>;
        worklogsToApprove: z.ZodDefault<z.ZodNumber>;
        pendingLeaveRequests: z.ZodDefault<z.ZodNumber>;
        leaveRequestsToApprove: z.ZodDefault<z.ZodNumber>;
        pendingDocuments: z.ZodDefault<z.ZodNumber>;
        documentsToReview: z.ZodDefault<z.ZodNumber>;
        teamInvitations: z.ZodDefault<z.ZodNumber>;
        pendingTeamTasks: z.ZodDefault<z.ZodNumber>;
        totalPendingItems: z.ZodDefault<z.ZodNumber>;
        totalUrgentItems: z.ZodDefault<z.ZodNumber>;
        totalOverdueItems: z.ZodDefault<z.ZodNumber>;
        highPriorityItems: z.ZodDefault<z.ZodNumber>;
        mediumPriorityItems: z.ZodDefault<z.ZodNumber>;
        lowPriorityItems: z.ZodDefault<z.ZodNumber>;
        itemsDueToday: z.ZodDefault<z.ZodNumber>;
        itemsDueThisWeek: z.ZodDefault<z.ZodNumber>;
        itemsDueThisMonth: z.ZodDefault<z.ZodNumber>;
        workloadLevel: z.ZodDefault<z.ZodEnum<["LOW", "MODERATE", "HIGH", "CRITICAL"]>>;
        estimatedHoursToComplete: z.ZodOptional<z.ZodNumber>;
        lastUpdated: z.ZodDate;
        createdAt: z.ZodDate;
    }, "strip", z.ZodTypeAny, {
        id: string;
        date: Date;
        createdAt: Date;
        userId: string;
        pendingCases: number;
        urgentCases: number;
        overdueCases: number;
        pendingTasks: number;
        urgentTasks: number;
        overdueTasks: number;
        personalTasks: number;
        adminTasks: number;
        bizDevTasks: number;
        pendingSubtasks: number;
        urgentSubtasks: number;
        overdueSubtasks: number;
        upcomingHearings: number;
        hearingsThisWeek: number;
        hearingsToday: number;
        pendingOrders: number;
        ordersToExecute: number;
        overdueOrders: number;
        pendingWorklogs: number;
        worklogsToApprove: number;
        pendingLeaveRequests: number;
        leaveRequestsToApprove: number;
        pendingDocuments: number;
        documentsToReview: number;
        teamInvitations: number;
        pendingTeamTasks: number;
        totalPendingItems: number;
        totalUrgentItems: number;
        totalOverdueItems: number;
        highPriorityItems: number;
        mediumPriorityItems: number;
        lowPriorityItems: number;
        itemsDueToday: number;
        itemsDueThisWeek: number;
        itemsDueThisMonth: number;
        workloadLevel: "LOW" | "HIGH" | "CRITICAL" | "MODERATE";
        lastUpdated: Date;
        estimatedHoursToComplete?: number | undefined;
    }, {
        id: string;
        date: Date;
        createdAt: Date;
        userId: string;
        lastUpdated: Date;
        pendingCases?: number | undefined;
        urgentCases?: number | undefined;
        overdueCases?: number | undefined;
        pendingTasks?: number | undefined;
        urgentTasks?: number | undefined;
        overdueTasks?: number | undefined;
        personalTasks?: number | undefined;
        adminTasks?: number | undefined;
        bizDevTasks?: number | undefined;
        pendingSubtasks?: number | undefined;
        urgentSubtasks?: number | undefined;
        overdueSubtasks?: number | undefined;
        upcomingHearings?: number | undefined;
        hearingsThisWeek?: number | undefined;
        hearingsToday?: number | undefined;
        pendingOrders?: number | undefined;
        ordersToExecute?: number | undefined;
        overdueOrders?: number | undefined;
        pendingWorklogs?: number | undefined;
        worklogsToApprove?: number | undefined;
        pendingLeaveRequests?: number | undefined;
        leaveRequestsToApprove?: number | undefined;
        pendingDocuments?: number | undefined;
        documentsToReview?: number | undefined;
        teamInvitations?: number | undefined;
        pendingTeamTasks?: number | undefined;
        totalPendingItems?: number | undefined;
        totalUrgentItems?: number | undefined;
        totalOverdueItems?: number | undefined;
        highPriorityItems?: number | undefined;
        mediumPriorityItems?: number | undefined;
        lowPriorityItems?: number | undefined;
        itemsDueToday?: number | undefined;
        itemsDueThisWeek?: number | undefined;
        itemsDueThisMonth?: number | undefined;
        workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
        estimatedHoursToComplete?: number | undefined;
    }>;
    recentActivity: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodString;
        title: z.ZodString;
        priority: z.ZodString;
        dueDate: z.ZodOptional<z.ZodDate>;
        createdAt: z.ZodDate;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: string;
        createdAt: Date;
        title: string;
        priority: string;
        dueDate?: Date | undefined;
    }, {
        id: string;
        type: string;
        createdAt: Date;
        title: string;
        priority: string;
        dueDate?: Date | undefined;
    }>, "many">;
    upcomingDeadlines: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodString;
        title: z.ZodString;
        dueDate: z.ZodDate;
        priority: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: string;
        title: string;
        priority: string;
        dueDate: Date;
    }, {
        id: string;
        type: string;
        title: string;
        priority: string;
        dueDate: Date;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    userId: string;
    userName: string;
    userRole: string;
    summary: {
        id: string;
        date: Date;
        createdAt: Date;
        userId: string;
        pendingCases: number;
        urgentCases: number;
        overdueCases: number;
        pendingTasks: number;
        urgentTasks: number;
        overdueTasks: number;
        personalTasks: number;
        adminTasks: number;
        bizDevTasks: number;
        pendingSubtasks: number;
        urgentSubtasks: number;
        overdueSubtasks: number;
        upcomingHearings: number;
        hearingsThisWeek: number;
        hearingsToday: number;
        pendingOrders: number;
        ordersToExecute: number;
        overdueOrders: number;
        pendingWorklogs: number;
        worklogsToApprove: number;
        pendingLeaveRequests: number;
        leaveRequestsToApprove: number;
        pendingDocuments: number;
        documentsToReview: number;
        teamInvitations: number;
        pendingTeamTasks: number;
        totalPendingItems: number;
        totalUrgentItems: number;
        totalOverdueItems: number;
        highPriorityItems: number;
        mediumPriorityItems: number;
        lowPriorityItems: number;
        itemsDueToday: number;
        itemsDueThisWeek: number;
        itemsDueThisMonth: number;
        workloadLevel: "LOW" | "HIGH" | "CRITICAL" | "MODERATE";
        lastUpdated: Date;
        estimatedHoursToComplete?: number | undefined;
    };
    recentActivity: {
        id: string;
        type: string;
        createdAt: Date;
        title: string;
        priority: string;
        dueDate?: Date | undefined;
    }[];
    upcomingDeadlines: {
        id: string;
        type: string;
        title: string;
        priority: string;
        dueDate: Date;
    }[];
}, {
    userId: string;
    userName: string;
    userRole: string;
    summary: {
        id: string;
        date: Date;
        createdAt: Date;
        userId: string;
        lastUpdated: Date;
        pendingCases?: number | undefined;
        urgentCases?: number | undefined;
        overdueCases?: number | undefined;
        pendingTasks?: number | undefined;
        urgentTasks?: number | undefined;
        overdueTasks?: number | undefined;
        personalTasks?: number | undefined;
        adminTasks?: number | undefined;
        bizDevTasks?: number | undefined;
        pendingSubtasks?: number | undefined;
        urgentSubtasks?: number | undefined;
        overdueSubtasks?: number | undefined;
        upcomingHearings?: number | undefined;
        hearingsThisWeek?: number | undefined;
        hearingsToday?: number | undefined;
        pendingOrders?: number | undefined;
        ordersToExecute?: number | undefined;
        overdueOrders?: number | undefined;
        pendingWorklogs?: number | undefined;
        worklogsToApprove?: number | undefined;
        pendingLeaveRequests?: number | undefined;
        leaveRequestsToApprove?: number | undefined;
        pendingDocuments?: number | undefined;
        documentsToReview?: number | undefined;
        teamInvitations?: number | undefined;
        pendingTeamTasks?: number | undefined;
        totalPendingItems?: number | undefined;
        totalUrgentItems?: number | undefined;
        totalOverdueItems?: number | undefined;
        highPriorityItems?: number | undefined;
        mediumPriorityItems?: number | undefined;
        lowPriorityItems?: number | undefined;
        itemsDueToday?: number | undefined;
        itemsDueThisWeek?: number | undefined;
        itemsDueThisMonth?: number | undefined;
        workloadLevel?: "LOW" | "HIGH" | "CRITICAL" | "MODERATE" | undefined;
        estimatedHoursToComplete?: number | undefined;
    };
    recentActivity: {
        id: string;
        type: string;
        createdAt: Date;
        title: string;
        priority: string;
        dueDate?: Date | undefined;
    }[];
    upcomingDeadlines: {
        id: string;
        type: string;
        title: string;
        priority: string;
        dueDate: Date;
    }[];
}>;
export declare const UserPendingSummaryStatisticsSchema: z.ZodObject<{
    totalUsers: z.ZodNumber;
    usersWithPendingItems: z.ZodNumber;
    usersWithOverdueItems: z.ZodNumber;
    usersWithUrgentItems: z.ZodNumber;
    averagePendingItemsPerUser: z.ZodNumber;
    workloadDistribution: z.ZodObject<{
        low: z.ZodNumber;
        moderate: z.ZodNumber;
        high: z.ZodNumber;
        critical: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        low: number;
        high: number;
        critical: number;
        moderate: number;
    }, {
        low: number;
        high: number;
        critical: number;
        moderate: number;
    }>;
    topUsersByPendingItems: z.ZodArray<z.ZodObject<{
        userId: z.ZodString;
        userName: z.ZodString;
        pendingItems: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        userId: string;
        userName: string;
        pendingItems: number;
    }, {
        userId: string;
        userName: string;
        pendingItems: number;
    }>, "many">;
    mostCommonPendingTypes: z.ZodArray<z.ZodObject<{
        type: z.ZodString;
        count: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        type: string;
        count: number;
    }, {
        type: string;
        count: number;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    totalUsers: number;
    usersWithPendingItems: number;
    usersWithOverdueItems: number;
    usersWithUrgentItems: number;
    averagePendingItemsPerUser: number;
    workloadDistribution: {
        low: number;
        high: number;
        critical: number;
        moderate: number;
    };
    topUsersByPendingItems: {
        userId: string;
        userName: string;
        pendingItems: number;
    }[];
    mostCommonPendingTypes: {
        type: string;
        count: number;
    }[];
}, {
    totalUsers: number;
    usersWithPendingItems: number;
    usersWithOverdueItems: number;
    usersWithUrgentItems: number;
    averagePendingItemsPerUser: number;
    workloadDistribution: {
        low: number;
        high: number;
        critical: number;
        moderate: number;
    };
    topUsersByPendingItems: {
        userId: string;
        userName: string;
        pendingItems: number;
    }[];
    mostCommonPendingTypes: {
        type: string;
        count: number;
    }[];
}>;
export declare const UserPendingSummaryRefreshSchema: z.ZodObject<{
    userId: z.ZodOptional<z.ZodString>;
    forceRefresh: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    forceRefresh: boolean;
    userId?: string | undefined;
}, {
    userId?: string | undefined;
    forceRefresh?: boolean | undefined;
}>;
export type UserPendingSummary = z.infer<typeof UserPendingSummarySchema>;
export type CreateUserPendingSummary = z.infer<typeof CreateUserPendingSummarySchema>;
export type UpdateUserPendingSummary = z.infer<typeof UpdateUserPendingSummarySchema>;
export type UserPendingSummarySearch = z.infer<typeof UserPendingSummarySearchSchema>;
export type UserPendingSummaryList = z.infer<typeof UserPendingSummaryListSchema>;
export type UserPendingSummaryWithUser = z.infer<typeof UserPendingSummaryWithUserSchema>;
export type UserPendingSummaryDashboard = z.infer<typeof UserPendingSummaryDashboardSchema>;
export type UserPendingSummaryStatistics = z.infer<typeof UserPendingSummaryStatisticsSchema>;
export type UserPendingSummaryRefresh = z.infer<typeof UserPendingSummaryRefreshSchema>;
//# sourceMappingURL=user-pending-summary.d.ts.map